### ISSUE TITLE
Raspberry Pi CM4 on Waveshare not booting

### ISSUE THREAD

**Issue by agners** [home-assistant/operating-system#2492] opened 2023-04-20 08:42 UTC
I'm using RPI CM4 with eMMC on Waveshare board with NVMe.
eMMC is unused due to known issues with NVMe, however after upgrade OS doesn't boot at all.
If connected, screen is blank, and as I understand it all ends on U-Boot.
Am I getting it right?

1. PI EEPROM is configured to boot from NVMe, and successfully does that by passing control to U-Boot (which was updated as a part of HAOS - #2234)
2. U-Boot fails to detect the NVMe for some reason (`Device 0: unknown device`?) and tries to boot via network (PXE)
3. HAOS is not even booted

```
...................................................................

U-Boot 2023.01 (Apr 17 2023 - 11:52:08 +0000)

DRAM:  512 MiB (effective 3.4 GiB)
RPI Compute Module 4 (0xc03141)
Core:  208 devices, 16 uclasses, devicetree: board
MMC:   mmcnr@7e300000: 1, mmc@7e340000: 0
Loading Environment from nowhere... OK
In:    serial
Out:   serial
Err:   serial
Net:   eth0: ethernet@7d580000
PCIe BRCM: link up, 5.0 Gbps x1 (SSC)
starting USB...
No working controllers found
switch to partitions #0, OK
mmc0(part 0) is current device
** No partition table - mmc 0 **
Couldn't find partition mmc 0:1
Card did not respond to voltage select! : -110
MMC Device 2 not found
no mmc device at slot 2

Device 0: unknown device
starting USB...
No working controllers found
USB is stopped. Please issue 'usb start' first.
starting USB...
No working controllers found
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
missing environment variable: pxeuuid
Retrieving file: pxelinux.cfg/01-e4-5f-01-b8-d2-51
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
Retrieving file: pxelinux.cfg/00000000
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
Retrieving file: pxelinux.cfg/0000000
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
Retrieving file: pxelinux.cfg/000000
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
Retrieving file: pxelinux.cfg/00000
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
Retrieving file: pxelinux.cfg/0000
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
Retrieving file: pxelinux.cfg/000
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
Retrieving file: pxelinux.cfg/00
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
Retrieving file: pxelinux.cfg/0
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
Retrieving file: pxelinux.cfg/default-arm-bcm283x-rpi
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
Retrieving file: pxelinux.cfg/default-arm-bcm283x
ethernet@7d580000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
bcmgenet: PHY startup failed: -110
Retrieving file: pxelinux.cfg/default-arm
ethernet@7d580000 Waiting for PHY auto negotiation to complete....
```

Also shared here: https://github.com/home-assistant/operating-system/issues/1887#issuecomment-1513719758

_Originally posted by @maxromanovsky in https://github.com/home-assistant/operating-system/issues/2480#issuecomment-1514530249_

**Comment by agners** [comment] 2023-04-20 08:44
Are these new symptoms with HAOS 10 (as in, it works with HAOS 9.5?)

Otherwise this is likely a duplicate of #1887.

**Comment by maxromanovsky** [comment] 2023-04-20 08:55
@agners it's new to HAOS 10, probably duplicate of #2480, where people share issues with both RPi4 USB SSDs and NVMes connected to CM4 base boards.

**Closed** 2023-04-20 09:58 UTC
Labels: duplicate, board/raspberrypi
