### ISSUE TITLE
RPI4 boot USB

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/operating-system#743] opened 2020-06-16 12:16 UTC
Hi
Is any chance to when we have beta Firmware with boot option USB on  RPI4 to write image on SSD and then connect it to USB and boot from USB ? Similary as on RPI3....

**Comment by VR29** [comment] 2020-06-18 07:20
According to [https://github.com/raspberrypi/rpi-eeprom/blob/master/firmware/release-notes.md](url) it is on stable now.

**Comment by pepeEL** [comment] 2020-06-18 07:26
correct link

**Comment by VR29** [comment] 2020-06-18 07:49
Corrected

**Comment by pepeEL** [comment] 2020-06-18 08:01
But when it share stable it was also correct image to option only burn on ssd and connect to USB and it willl be working ?

**Comment by pvizeli** [comment] 2020-06-19 10:43
Duplicate of #164

**Closed by pvizeli** 2020-06-19 10:43 UTC
