### ISSUE TITLE
Intel AX210 wifi not working

### ISSUE THREAD

**Issue by voed** [home-assistant/operating-system#2547] opened 2023-05-12 14:50 UTC
### Describe the issue you are experiencing

Just bought new wifi adapter for my Intel NUC and it does not works. After upgrading from 10.1 to the nightly release (11.0.dev20230511), it started once:
```
May 12 13:33:32 homeassistant kernel: iwlwifi 0000:02:00.0: enabling device (0000 -> 0002)
May 12 13:33:32 homeassistant kernel: iwlwifi 0000:02:00.0: api flags index 2 larger than supported by driver
May 12 13:33:32 homeassistant kernel: iwlwifi 0000:02:00.0: TLV_FW_FSEQ_VERSION: FSEQ Version: 0.0.2.36
May 12 13:33:32 homeassistant kernel: iwlwifi 0000:02:00.0: loaded firmware version 72.a764baac.0 ty-a0-gf-a0-72.ucode op_mode iwlmvm
May 12 13:33:33 homeassistant kernel: iwlwifi 0000:02:00.0: Detected Intel(R) Wi-Fi 6 AX210 160MHz, REV=0x420
May 12 13:33:33 homeassistant kernel: iwlwifi 0000:02:00.0: loaded PNVM version e4a49534
May 12 13:33:33 homeassistant kernel: iwlwifi 0000:02:00.0: Detected RF GF, rfid=0x10d000
May 12 13:33:33 homeassistant kernel: iwlwifi 0000:02:00.0: base HW address: f4:7b:09:ca:1d:45
May 12 13:33:33 homeassistant kernel: iwlwifi 0000:02:00.0 wlp2s0: renamed from wlan0
```
But after reboot it does not works anymore. Tried to put pnvm file to the /mnt/data/supervisor/firmware folder, but no changes.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

11.0.dev20230511

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

-

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the Host logs that might be useful for us?

```txt
May 12 14:00:08 homeassistant kernel: iwlwifi 0000:02:00.0: enabling device (0000 -> 0002)
May 12 14:00:08 homeassistant kernel: iwlwifi 0000:02:00.0: api flags index 2 larger than supported by driver
May 12 14:00:08 homeassistant kernel: iwlwifi 0000:02:00.0: TLV_FW_FSEQ_VERSION: FSEQ Version: 0.0.2.36
May 12 14:00:08 homeassistant kernel: iwlwifi 0000:02:00.0: loaded firmware version 72.a764baac.0 ty-a0-gf-a0-72.ucode op_mode iwlmvm
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: Detected Intel(R) Wi-Fi 6 AX210 160MHz, REV=0x420
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: Detected RF GF, rfid=0x10d000
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: Microcode SW error detected. Restarting 0x0.
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: Start IWL Error Log Dump:
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: Transport status: 0x0000004A, valid: 6
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: Loaded firmware version: 72.a764baac.0 ty-a0-gf-a0-72.ucode
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000071 | NMI_INTERRUPT_UMAC_FATAL
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x002002F0 | trm_hw_status0
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | trm_hw_status1
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004DB5D2 | branchlink2
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004D180A | interruptlink1
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004D180A | interruptlink2
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004DA32C | data1
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000010 | data2
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | data3
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | beacon time
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x000147E3 | tsf low
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | tsf hi
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | time gp1
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x0002866E | time gp2
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000001 | uCode revision type
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000048 | uCode version major
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0xA764BAAC | uCode version minor
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000420 | hw version
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00C89002 | board version
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x8008FD0D | hcmd
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00020000 | isr0
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x60000000 | isr1
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x48F00002 | isr2
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00C0000C | isr3
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | isr4
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | last cmd Id
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004DA32C | wait_event
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_control
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_duration
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_mhvalid
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_addr_match
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000009 | lmpm_pmg_sel
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | timestamp
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000024 | flow_handler
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: Start IWL Error Log Dump:
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: Transport status: 0x0000004A, valid: 7
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: PNVM data is missing, please install iwlwifi-ty-a0-gf-a0.pnvm
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x2010070D | PNVM_MISSING
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | umac branchlink1
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x8045F1D0 | umac branchlink2
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x0109912A | umac interruptlink1
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | umac interruptlink2
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000005 | umac data1
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0xDEADBEEF | umac data2
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0xDEADBEEF | umac data3
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000048 | umac major
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0xA764BAAC | umac minor
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00028668 | frame pointer
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0xC0885EA8 | stack pointer
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00010C00 | last host cmd
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | isr status reg
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: IML/ROM dump:
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000B03 | IML/ROM error/state
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00007FFE | IML/ROM data1
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000080 | IML/ROM WFPM_AUTH_KEY_0
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: Fseq Registers:
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x20000000 | FSEQ_ERROR_CODE
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x80440005 | FSEQ_TOP_INIT_VERSION
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00080009 | FSEQ_CNVIO_INIT_VERSION
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x0000A652 | FSEQ_OTP_VERSION
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000002 | FSEQ_TOP_CONTENT_VERSION
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x4552414E | FSEQ_ALIVE_TOKEN
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | FSEQ_CNVI_ID
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | FSEQ_CNVR_ID
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | CNVI_AUX_MISC_CHIP
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | CNVR_AUX_MISC_CHIP
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00009061 | CNVR_SCU_SD_REGS_SD_REG_DIG_DCDC_VTRIM
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000061 | CNVR_SCU_SD_REGS_SD_REG_ACTIVE_VDIG_MIRROR
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: WRT: Collecting data: ini trigger 13 fired (delay=0ms).
May 12 14:00:09 homeassistant kernel: iwlwifi 0000:02:00.0: Failed to run INIT ucode: -5
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: retry init count 0
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: Detected Intel(R) Wi-Fi 6 AX210 160MHz, REV=0x420
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: Microcode SW error detected. Restarting 0x0.
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: Start IWL Error Log Dump:
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: Transport status: 0x0000004A, valid: 6
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: Loaded firmware version: 72.a764baac.0 ty-a0-gf-a0-72.ucode
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000071 | NMI_INTERRUPT_UMAC_FATAL
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x002002F0 | trm_hw_status0
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | trm_hw_status1
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004DB5D2 | branchlink2
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004D180A | interruptlink1
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004D180A | interruptlink2
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004DA32C | data1
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000010 | data2
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | data3
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | beacon time
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x0001362D | tsf low
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | tsf hi
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | time gp1
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x000273E1 | time gp2
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000001 | uCode revision type
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000048 | uCode version major
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0xA764BAAC | uCode version minor
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000420 | hw version
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x18C89002 | board version
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x8008FD0D | hcmd
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00020000 | isr0
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x60000000 | isr1
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x48F00002 | isr2
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00C0000C | isr3
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | isr4
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | last cmd Id
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004DA32C | wait_event
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_control
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_duration
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_mhvalid
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_addr_match
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000009 | lmpm_pmg_sel
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | timestamp
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000024 | flow_handler
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: Start IWL Error Log Dump:
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: Transport status: 0x0000004A, valid: 7
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: PNVM data is missing, please install iwlwifi-ty-a0-gf-a0.pnvm
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x2010070D | PNVM_MISSING
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | umac branchlink1
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x8045F1D0 | umac branchlink2
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x0109912A | umac interruptlink1
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | umac interruptlink2
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000005 | umac data1
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0xDEADBEEF | umac data2
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0xDEADBEEF | umac data3
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000048 | umac major
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0xA764BAAC | umac minor
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x000273DB | frame pointer
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0xC0885EA8 | stack pointer
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00010C00 | last host cmd
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | isr status reg
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: IML/ROM dump:
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000B03 | IML/ROM error/state
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00007FF3 | IML/ROM data1
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000080 | IML/ROM WFPM_AUTH_KEY_0
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: Fseq Registers:
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x60000000 | FSEQ_ERROR_CODE
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00440007 | FSEQ_TOP_INIT_VERSION
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00080009 | FSEQ_CNVIO_INIT_VERSION
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x0000A652 | FSEQ_OTP_VERSION
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000002 | FSEQ_TOP_CONTENT_VERSION
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x4552414E | FSEQ_ALIVE_TOKEN
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | FSEQ_CNVI_ID
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | FSEQ_CNVR_ID
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | CNVI_AUX_MISC_CHIP
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | CNVR_AUX_MISC_CHIP
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00009061 | CNVR_SCU_SD_REGS_SD_REG_DIG_DCDC_VTRIM
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000061 | CNVR_SCU_SD_REGS_SD_REG_ACTIVE_VDIG_MIRROR
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: WRT: Collecting data: ini trigger 13 fired (delay=0ms).
May 12 14:00:10 homeassistant kernel: iwlwifi 0000:02:00.0: Failed to run INIT ucode: -5
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: retry init count 1
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: Detected Intel(R) Wi-Fi 6 AX210 160MHz, REV=0x420
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: Microcode SW error detected. Restarting 0x0.
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: Start IWL Error Log Dump:
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: Transport status: 0x0000004A, valid: 6
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: Loaded firmware version: 72.a764baac.0 ty-a0-gf-a0-72.ucode
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000071 | NMI_INTERRUPT_UMAC_FATAL
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x002082F0 | trm_hw_status0
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | trm_hw_status1
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004DB5D2 | branchlink2
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004D180A | interruptlink1
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004D180A | interruptlink2
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004DA32C | data1
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000010 | data2
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | data3
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | beacon time
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x000136AE | tsf low
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | tsf hi
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | time gp1
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00027461 | time gp2
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000001 | uCode revision type
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000048 | uCode version major
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0xA764BAAC | uCode version minor
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000420 | hw version
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x18C89002 | board version
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x8008FD0D | hcmd
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x20028000 | isr0
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x60000000 | isr1
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x48F00002 | isr2
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00C0000C | isr3
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | isr4
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | last cmd Id
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x004DA32C | wait_event
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_control
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_duration
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_mhvalid
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | l2p_addr_match
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000009 | lmpm_pmg_sel
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | timestamp
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000024 | flow_handler
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: Start IWL Error Log Dump:
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: Transport status: 0x0000004A, valid: 7
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: PNVM data is missing, please install iwlwifi-ty-a0-gf-a0.pnvm
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x2010070D | PNVM_MISSING
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | umac branchlink1
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x8045F1D0 | umac branchlink2
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x0109912A | umac interruptlink1
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | umac interruptlink2
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000005 | umac data1
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0xDEADBEEF | umac data2
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0xDEADBEEF | umac data3
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000048 | umac major
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0xA764BAAC | umac minor
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x0002745B | frame pointer
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0xC0885EA8 | stack pointer
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00010C00 | last host cmd
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000000 | isr status reg
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: IML/ROM dump:
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000B03 | IML/ROM error/state
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00007FFC | IML/ROM data1
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000080 | IML/ROM WFPM_AUTH_KEY_0
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: Fseq Registers:
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x60000100 | FSEQ_ERROR_CODE
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00440007 | FSEQ_TOP_INIT_VERSION
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00080009 | FSEQ_CNVIO_INIT_VERSION
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x0000A652 | FSEQ_OTP_VERSION
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000002 | FSEQ_TOP_CONTENT_VERSION
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x4552414E | FSEQ_ALIVE_TOKEN
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | FSEQ_CNVI_ID
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | FSEQ_CNVR_ID
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | CNVI_AUX_MISC_CHIP
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00400410 | CNVR_AUX_MISC_CHIP
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00009061 | CNVR_SCU_SD_REGS_SD_REG_DIG_DCDC_VTRIM
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: 0x00000061 | CNVR_SCU_SD_REGS_SD_REG_ACTIVE_VDIG_MIRROR
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: WRT: Collecting data: ini trigger 13 fired (delay=0ms).
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: Failed to run INIT ucode: -5
May 12 14:00:11 homeassistant kernel: iwlwifi 0000:02:00.0: retry init count 2
```
```


### System information

<html>
<body>
<!--StartFragment-->

Версія | core-2023.5.2
-- | --
Тип інсталяції | Home Assistant OS
Середовище розробки | false
Supervisor | true
Docker | true
Користувач | root
Віртуальне оточення | false
Версія Python | 3.10.11
Сімейство операційних систем | Linux
Версія операційної системи | 6.1.28
Архітектура ЦП | x86_64
Часовий пояс | Europe/Kiev
Каталог конфігурацій | /config

<!--EndFragment-->
</body>
</html>

### Additional information

_No response_

**Comment by agners** [comment] 2023-05-16 06:58
This is probably caused by #2542.

> But after reboot it does not works anymore. Tried to put pnvm file to the /mnt/data/supervisor/firmware folder, but no changes.

Probably the probing happens to early, at a point where `/mnt/data` is not mounted yet. We'll need to find a way to fix this.

But for your case, the right fix is to deploy the missing files as part of HAOS.

**Comment by agners** [comment] 2023-05-25 16:53
This should be resolved with the latest nightly builds.

**Closed by agners** 2023-05-25 16:53 UTC
Labels: bug, board/generic-x86-64

**Comment by voed** [comment] 2023-05-26 09:56
Works fine. Thanks.
