### ISSUE TITLE
You are in rescue mode

### ISSUE THREAD

**Issue by maykino** [home-assistant/operating-system#2295] opened 2023-01-03 15:12 UTC
### Describe the issue you are experiencing

Suddenly after a system reboot it seems to enter the rescue mode and there is no clear way out. Instructions shown here don't work: https://community.home-assistant.io/t/hass-os-6-0-vdi-after-upgrade-fails-every-boot-failed-to-start-grow-file-system-on-mnt-data/315819

After running umount -A /dev/disk/by-label/hassos-data I get this message: target is busy

Screencast: 
https://www.loom.com/share/9b014dba71eb4e1d882fdbf172bb8087

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

Not sure

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

NA

### Anything in the Supervisor logs that might be useful for us?

```txt
NA
```

### Anything in the Host logs that might be useful for us?

```txt
NA
```

**Comment by maykino** [comment] 2023-01-04 18:01
BUMP

**Comment by Batman313v** [comment] 2023-01-11 00:49
Also having this issue after newest update

**Comment by maykino** [comment] 2023-01-11 13:32
I ended up reinstalling the system from a backup.

**Comment by agners** [comment] 2023-01-25 13:11
This is essentially a duplicate of #1426.

From your screencast it seems that the data partition was still in use when you tried to fix the file system. I've posted an updated set of instruction at https://github.com/home-assistant/operating-system/issues/1426#issuecomment-1403583835.

Since you reinstalled from backup, I assume this can be closed. Sorry for the delay.

**Closed by agners** 2023-01-25 13:11 UTC
Labels: bug, board/generic-x86-64

**Comment by destiny-cob** [comment] 2024-02-10 04:28
After a power failure and server restart, homeassistant does not work. In the first line he writes: attempting to start up from: EFI Network... then the B rescue shell slot immediately jumps. And that's the end of it. Alas, I'm stupid, I admit, and I don't have a deposit, it works for me on HA heating, feeding the animals and water for them - PLEASE! help me to make it work what should i do? I tried washing and fsck but it didn't help. When updating, a backup is made by itself - does it then delete itself? or can it be found somewhere? I don't understand Linux at all, I have no idea what to do with it. Otherwise, HA works for me in ESXi where it is installed directly as an .ova image (I don't know if it affects anything). No changes were made to the hardware. Resp. I replaced the RAM memory. But that shouldn't have any effect...
