### ISSUE TITLE
HAOS 10.1 Raspberrypi 3 B+ USB Boot not working

### ISSUE THREAD

**Issue by lodzen** [home-assistant/operating-system#2527] opened 2023-05-01 09:40 UTC
### Describe the issue you are experiencing

With Version 10.1 Boot from USB is not working anymore on Raspberrypi 3 B+.
I tried to boot Raspbian to exclude Adapter issues or SSD Issues. With this OS its working out of the Box.
What i observed is that U-Boot is loaded then it tries to boot from LAN it seems that the Kernel cannot be found.

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

10.1

### Did you upgrade the Operating System.

No

### Steps to reproduce the issue

1. Flash fresh HAOS with RPI Imager
2. Try to boot from created SSD

### Anything in the Supervisor logs that might be useful for us?

```txt
No logs available
```

### Anything in the Host logs that might be useful for us?

```txt
Only U-Boot seems to be loaded but the Kernel cannot be found.
```

**Comment by agners** [comment] 2023-05-01 12:10
Duplicate of #2480.

My test setup involving a USB flash drive works with Raspberry Pi 3 B+ & HAOS 10.1, so this is not a generic problem. Unfortunately there seem many variables leading to a working or non-working USB SSD boot :cry: 

Please state exact configuration in issue #2480 like USB SSD adapter, the type and make of the SSD attached, your power supply and USB hubs if used.

**Closed by agners** 2023-05-01 12:10 UTC
Labels: bug, board/raspberrypi
