### ISSUE TITLE
HA not working after update to OS 11

### ISSUE THREAD

**Issue by leejoow** [home-assistant/operating-system#2863] opened 2023-10-25 14:58 UTC
### Describe the issue you are experiencing

After updating this morning to the latest OS my installation is not working anymore. I'm using a ODroid M1.
I can ping the device, but HA will not start.

When connected to a monitor, it stays at the message "Waiting for the HomeAssistant CLI te bo ready"

### What operating system image do you use?

odroid-m1 (Hardkernel ODROID-M1)

### What version of Home Assistant Operating System is installed?

unknown at this moment

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Install OS 11

### Anything in the Supervisor logs that might be useful for us?

```txt
I cannot access the logs, because my system does not start
```

### Anything in the Host logs that might be useful for us?

```txt
I cannot access the logs, because my system does not start
```

**Comment by agners** [comment] 2023-10-25 22:16
This is a duplicate of #2822 and will be addressed in 11.1. Check this comment on how to resolve https://github.com/home-assistant/operating-system/issues/2822#issuecomment-1779485019.

**Closed by agners** 2023-10-25 22:16 UTC
Labels: bug, duplicate, board/odroid
