### ISSUE TITLE
After upgrade to Home Assistant 8.0 OVA, the VM fails to shut down.

### ISSUE THREAD

**Issue by csimonosian** [home-assistant/operating-system#1923] opened 2022-05-18 16:29 UTC
### Describe the issue you are experiencing

I upgraded from 7.6 to 8.0 and the VirtualBox VM now fails to shut down. It won't respond to the Virtual Box "Send shutdown signal" nor the "Power off" command, and doesn't respond to the command line:

vboxmanage controlvm "Home Assistant" acpipowerbutton

I can only recover by restoring OS 7.6 using a previously-exported backup of the VM. Note that it does shut down by using the Shutdown Host command from within Home Assistant itself. It just doesn't seem to respond to VirtualBox shutdown commands.

I have tried the upgrade twice, with the same results.

I am using VirtualBox v6.1.34.

### What operating system image do you use?

ova (for Virtual Machines)

### What version of Home Assistant Operating System is installed?

8.0

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Upgrade the OS to 8.0
2. Try to shut the VM down after it's restarted using one of the shutdown methods.
3. Home Assistant does not shut down.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
These are the last few entries, but they just look like bootup messages, nothing related to when I tried to shut it down.

[   43.631625] audit: type=1327 audit(1652890421.494:120): proctitle=2F7573722F7362696E2F69707461626C6573002D2D77616974002D4C002D6E
[   43.634302] audit: type=1325 audit(1652890421.494:121): table=nat family=2 entries=5 op=xt_replace pid=1823 subj==unconfined comm="iptables"
[   43.651283] eth0: renamed from vethe12a0b5
[   43.651504] IPv6: ADDRCONF(NETDEV_CHANGE): veth880c02e: link becomes ready
[   43.651532] hassio: port 5(veth880c02e) entered blocking state
[   43.651534] hassio: port 5(veth880c02e) entered forwarding state
[   45.740478] hassio: port 6(vethae68fd5) entered blocking state
[   45.740483] hassio: port 6(vethae68fd5) entered disabled state
[   45.740680] device vethae68fd5 entered promiscuous mode
[   46.203008] eth0: renamed from vethce31f5e
[   46.215715] IPv6: ADDRCONF(NETDEV_CHANGE): vethae68fd5: link becomes ready
[   46.215743] hassio: port 6(vethae68fd5) entered blocking state
[   46.215745] hassio: port 6(vethae68fd5) entered forwarding state
[   96.821247] kauditd_printk_skb: 56 callbacks suppressed
[   96.821251] audit: type=1334 audit(1652890477.090:140): prog-id=0 op=UNLOAD
[   96.821256] audit: type=1334 audit(1652890477.090:141): prog-id=0 op=UNLOAD
[   96.827410] audit: type=1334 audit(1652890477.096:142): prog-id=0 op=UNLOAD
[   96.827416] audit: type=1334 audit(1652890477.096:143): prog-id=0 op=UNLOAD
```

### Anything in the Host logs that might be useful for us?

```txt
These are the last few entries, but there is no timestramp on them so can't tell if they're relevent to the shutdown command. They are all look like bootup messages.

[   43.631625] audit: type=1327 audit(1652890421.494:120): proctitle=2F7573722F7362696E2F69707461626C6573002D2D77616974002D4C002D6E
[   43.634302] audit: type=1325 audit(1652890421.494:121): table=nat family=2 entries=5 op=xt_replace pid=1823 subj==unconfined comm="iptables"
[   43.651283] eth0: renamed from vethe12a0b5
[   43.651504] IPv6: ADDRCONF(NETDEV_CHANGE): veth880c02e: link becomes ready
[   43.651532] hassio: port 5(veth880c02e) entered blocking state
[   43.651534] hassio: port 5(veth880c02e) entered forwarding state
[   45.740478] hassio: port 6(vethae68fd5) entered blocking state
[   45.740483] hassio: port 6(vethae68fd5) entered disabled state
[   45.740680] device vethae68fd5 entered promiscuous mode
[   46.203008] eth0: renamed from vethce31f5e
[   46.215715] IPv6: ADDRCONF(NETDEV_CHANGE): vethae68fd5: link becomes ready
[   46.215743] hassio: port 6(vethae68fd5) entered blocking state
[   46.215745] hassio: port 6(vethae68fd5) entered forwarding state
[   96.821247] kauditd_printk_skb: 56 callbacks suppressed
[   96.821251] audit: type=1334 audit(1652890477.090:140): prog-id=0 op=UNLOAD
[   96.821256] audit: type=1334 audit(1652890477.090:141): prog-id=0 op=UNLOAD
[   96.827410] audit: type=1334 audit(1652890477.096:142): prog-id=0 op=UNLOAD
[   96.827416] audit: type=1334 audit(1652890477.096:143): prog-id=0 op=UNLOAD
```

## System Health

version | core-2022.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.15.38
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.0
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.2
docker_version | 20.10.14
disk_total | 22.9 GB
disk_used | 6.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.6.1), Z-Wave JS (0.1.58)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

**Comment by agners** [comment] 2022-05-18 22:48
Duplicate of #1896

**Closed by agners** 2022-05-18 22:48 UTC
Labels: bug
