### ISSUE TITLE
Tinker Board S does not boot from eMMC with HassOS 4.5 release/update

### ISSUE THREAD

**Issue by mbo18** [home-assistant/operating-system#650] opened 2020-05-01 12:51 UTC
**HassOS release with the issue:**

HassOS 4.5

**Supervisor logs:**

None, does not boot from eMMC. Nothing on screen (HDMI). Does boot from SD card

**Journal logs:**

None

**Kernel logs:**

None

**Description of problem:**
Just tried to upgrade from HassOS 3.13 to 4.5 from 'import from USB' and my Tinker Board S did not boot anymore. Tried to flash 4.5 directly to eMMC and it does not boot. Flash to SD card and it boot fine.
It seems that boot from eMMC is not working anymore with HassOS 4.5

**Comment by venditdevs** [comment] 2020-05-01 13:26
That would make sense  why my Odroid N2 isn't booting anymore from SD. Because the Odroid-N2 must select MMC to get it to boot Home Assistant from SD. I know: that doesn't make sense but it really needs  it ;).
So basically we can say: EMMC booting is broken in HassOS4.5.

**Comment by Multipage** [comment] 2020-05-01 13:35
That would make sense why my Odroid N2 isn't booting anymore from SD. Because the Odroid-N2 must select MMC to get it to boot Home Assistant from SD. I know: that doesn't make sense but it really needs it ;).
So basically we can say: EMMC booting is broken in HassOS4.5.

**Comment by alex7614** [comment] 2020-05-03 11:59
Same problem on Tinker S on eMMC. I flahed back to 4.4 on eMMC until new version.

**Comment by mbo18** [comment] 2020-05-06 18:05
It seems that it will not be solved as Pvizeli has no tinker board S to make tests and rbray89 who worked on it has leaved the project

**Comment by mbo18** [comment] 2020-05-07 12:51
@pvizeli Maybe you should block OS update for this specific board? because people will click on update and it won't boot anymore...
What is the best way now? SD card + offloading data to eMMC?

**Comment by pvizeli** [comment] 2020-05-08 07:34
@Multipage the N2 was just a bug in the official kernel from the manufacture and is fix with 4.6. The Tinker was just designed for usage on Tinker (without S) because for that is needs a new image. It's my wrong that I did not look exactly what Ryan did. But also on the official website, we just list the Tinker board without S (https://www.home-assistant.io/hassio/installation). However, Look like there are some people, maybe someone of you will join the project and spend some days per year into maintenance and responsible for issues.

**Comment by cybergrimes** [comment] 2020-06-01 13:03
What is this? I've had a Tinker Board S running Home Assistant since December 2018. We have had other non-booting OS image issues in the past for the S model that were fixed.

**Comment by cybergrimes** [comment] 2020-06-01 13:06
Here for example, we had issues with booting eMMC on Tinker Board S and the problem was resolved. No mention of S model not being supported: https://github.com/home-assistant/operating-system/issues/344

**Comment by cybergrimes** [comment] 2020-06-01 13:09
> 
> 
> @pvizeli Maybe you should block OS update for this specific board? because people will click on update and it won't boot anymore...
> What is the best way now? SD card + offloading data to eMMC?

What have you decided to do with your setup? I have been on Tinker Board S since December 2019 without issue. We've both posted here in the past with regards to S model not booting after OS updates. I'm a little disappointed to say the least, not expecting to need new hardware.

**Comment by mbo18** [comment] 2020-06-01 13:22
Well, it won't help you :) 
I've bought a used NUC (from 2015) with way more RAM and with an SSD. I've made a good choice: HA restart in 12s, everything is smoother and I can run more addons

**Comment by cybergrimes** [comment] 2020-06-01 13:26
Yeah, I just spied you on forums and saw that. 
I'll consider that option-- no luck with data partition offload?

**Comment by mbo18** [comment] 2020-06-01 13:58
I didn't even tried. I was looking for a NUC before the last HassOS release. When I saw that boot from eMMC was removed, choice was made

**Comment by cybergrimes** [comment] 2020-06-01 16:08
Gotcha, moved mine to a VirtualBox until I figure out something else (if anything)

Cheers

**Comment by anthfarr** [comment] 2020-06-03 15:25
I have the same issue. Is there an easy way to downgrade hassos ?

**Comment by cybergrimes** [comment] 2020-06-03 18:53
@pvizeli any chance you would do take donations to get a Tinker Board S like you did a couple years ago with original Tinker Board? https://github.com/home-assistant/operating-system/issues/33

**Comment by junologue** [comment] 2020-06-05 15:59
> We are not currently expanding supported boards. It takes ongoing maintenance to test every update on every board and we don't have the resources for this right now.

Totally understand. But since Hassos 3.13 works very well for my tinker S still, for how long could i continue to upgrade Home Assistant Core with 3.13 as a base? Does it have a limit?

**Comment by jpjcrossi** [comment] 2020-06-12 12:05
I'm little bit worrying because it was working very well and after an update it just stopped to work.
Now I'm use hassio on SD card and seems to me very unstable.
The Home Assistant just freezing whihout any reason.  :(
Please, I'm beg you. Consider provide support for the eMMC for Hassio on Tinker Board S again.

**Comment by junologue** [comment] 2020-06-12 12:12
> We are not currently expanding supported boards. It takes ongoing maintenance to test every update on every board and we don't have the resources for this right now.

-

I understand. Tinkerboard S is just to good to be left behind though! So please consider it. The emmc is so stable compared to my Pi 3B+ even with the most high end SD-card.

In what version did you drop the support? Is 3.13 really the last one? I’ve heard someone talked about 3.8, but haven’t tried yet.

**Comment by poelsevev** [comment] 2020-07-26 07:57
I'm using 3.9 on my tinkerboard S. Seems to me the issue comes with all version 4.x 
The tinkerboard S has run flawless for me so hope they will fix this issue in the future.

**Comment by junologue** [comment] 2020-07-26 09:56
I am using version 4.4 with on Tinkerboard S without any issues. Works just as fine as 3.13

**Comment by jdbrookes** [comment] 2020-07-26 10:29
> Right now I am using version 4.4 with on Tinkerboard S without any issues. Works just as fine as 3.13
> 
> Anyone who knows how to disable and remove the OS update notification though?
> 
> ![5A0F5DDD-6E6C-4764-980D-E7366151D30A](https://user-images.githubusercontent.com/38961702/88476248-4a01bc00-cf37-11ea-8f8c-effab73e01c0.jpeg)

I think the issue is with booting directly from eMMC, without an SD card. It would be great if support for this had been reintroduced? 

I've not yet bit the bullet and moved everything to microsd, and then done the datactl command. If anyone has experience with doing this on a tinkerboard s and would be able to do a brief writeup it would be appreciated! I think I would need to wipe the eMMC before flashing to microsd but I'm not sure how to do this.

**Comment by junologue** [comment] 2020-07-26 16:37
I am running on emmc, hassos 4.4
Tinkerboard S

**Comment by jdbrookes** [comment] 2020-07-31 21:15
> I am running on emmc, hassos 4.4
> Tinkerboard S

I don't think I'm brave enough to try updating to the latest version!

**Comment by poelsevev** [comment] 2020-08-04 19:12
I installed the versions backwards until I found one that worked, and for me that was 3.9, but I can't remember if 4.4 was out then. But all versions worked with SD card. So that's why I gues thought 4.x is the issue with emmc boot. junologue, did you do anything else beside run the install for tinkerboard??

**Comment by junologue** [comment] 2020-08-04 21:27
Nope, i just did a clean install, then restored previous snapshots :)

**Comment by pbalogh77** [comment] 2020-08-09 13:46
I'm struggling with the same. Why is this issue closed?

**Comment by frenck** [comment] 2020-08-09 13:50
@pbalogh77 Because the Tinkerboard S is not a supported board. For supported hardware see:

<https://github.com/home-assistant/architecture/blob/master/adr/0015-home-assistant-os.md#supported-boardshardwaremachines>

**Comment by pbalogh77** [comment] 2020-08-09 20:48
The Tinkerboard S is just a Tinkerboard with eMMC and has been a supported board for years. Is this a bug that needs fixing (in which case I'm happy to help) or a conscious decision to abandon support, in which case I should either stay with v4.4 or move to a new HW? At least it would have been nice to communicate this as a breaking change :-(

**Comment by pbalogh77** [comment] 2020-08-10 20:29
Thanks, I understand. Maybe I should be moving to a different HW sooner or
later...

**Comment by jpjcrossi** [comment] 2020-08-10 22:07
I didn't know that board was discontinued. I tried looking for more information about this but I didn't find it.
It's a pity ... :(

**Comment by poelsevev** [comment] 2020-08-18 20:43
is this issue with tinkerboard emmc fixed? i notised there where something doen regarding tinker s on release 4.7

**Comment by dyrvigk** [comment] 2020-08-21 07:02
hi frenck i dont understand you say the tinker board s i discontinued but it dosent say that anywhere and i can find more than a 100 places just here in denmark where you can buy 

kenn

**Comment by zerblatt007** [comment] 2020-08-26 14:14
Amazon seems to think the Tinker board S is not discontinued:
https://www.amazon.com/ASUS-Tinker-Board-connectivity-Motherboards/dp/B00FS83U42?th=1
"Is Discontinued By Manufacturer | No"

If someone donates a board to a developer, would that make them supported or is this something you guys rather would not do?

**Comment by agners** [comment] 2020-09-03 12:27
I do have one of those board now, I am going to have a look.

**Comment by agners** [comment] 2020-09-09 19:12
The good news is the fix landed in `dev`. The bad news is I broke the Tinker build in the process :-(

I already made a merge request to fix it (https://github.com/home-assistant/operating-system/pull/854). So a fixed version will come at one point :-)

**Comment by jpjcrossi** [comment] 2020-09-09 19:23
Great job. I'll test it as soon as available  that new feature.
Many thanks! 👍

**Comment by zerblatt007** [comment] 2020-09-09 19:36
Really glad to hear this Stefan!
This will be Dev 5 build 3 per chance?

**Comment by junologue** [comment] 2020-09-09 22:51
Nice Agners!

So this means Tinkerboard S will soon be supported in an official build again?

**Comment by pvizeli** [comment] 2020-09-12 21:54
Fix 5.2

**Closed by pvizeli** 2020-09-12 21:54 UTC

**Comment by anthfarr** [comment] 2020-12-24 10:00
Hi - sorry to comment on a closed issue however I'm confused. This issue is marked as fixed, however the official docs do not mention tinkerboard S is supported (only tinkerboard is mentioned) - Does this mean I can use tinkerboard S (using emmc) or not?

**Comment by poelsevev** [comment] 2021-01-01 09:02
> Hi - sorry to comment on a closed issue however I'm confused. This issue is marked as fixed, however the official docs do not mention tinkerboard S is supported (only tinkerboard is mentioned) - Does this mean I can use tinkerboard S (using emmc) or not?

-----

You can use the Tinkerboard S. I have Been using it for a couple of years and works great with a large nummer of z-wave and zigbee devices and a gold bunch of automations running. I just keep a backup on a SD card just inn case something happens during updates.
