### ISSUE TITLE
Wifi Channel 13 Issue

### ISSUE THREAD

**Issue by TonsiTT** [home-assistant/operating-system#2755] opened 2023-09-15 23:01 UTC
### Describe the issue you are experiencing

My WIFI is currently set to channel 13, which makes the RPi unable to detect it. I installed the 'iw' utility through the 'Advance SSH and Web Terminal' addon and used the command 'iw reg set GB'. I went to settings, and voila, it was detecting my wifi even without restarting anything.

Now, the issue arises as soon as the RPi/Haos is rebooted, it reverts back to default, and my RPi is unable to connect anymore. Is there any way to permanently change it so it detects channel 13 wifi AP's?

### What operating system image do you use?

rpi3-64 (Raspberry Pi 3 64-bit OS)

### What version of Home Assistant Operating System is installed?

Latest

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Set Wi-Fi channel to 13 
2. Search for wifi in system

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

**Comment by agners** [comment] 2023-09-19 06:39
For now we don't have a built-in method to set the regulatory domain. This makes the kernel to fallback to the global regulatory domain (00), which does not allow all channels.

You can edit `cmdline.txt` on the first partition of the SD card to set a regulatory domain, see also https://github.com/home-assistant/operating-system/issues/1530#issuecomment-912745307.

I am closing this as duplicate of #1530.

**Closed by agners** 2023-09-19 06:39 UTC
Labels: bug, duplicate, board/raspberrypi
