### ISSUE TITLE
[FR] RPI4 USB Boot

### ISSUE THREAD

**Issue by vistalba** [home-assistant/operating-system#734] opened 2020-06-08 16:56 UTC
As USB Boot for RPi4 is now possible with updated eeprom (beta) if would be nice if the image cloud be updated so that I can boot it from a USB3 SSD which is much faster than SD-Card.

**Comment by balloob** [comment] 2020-06-08 17:57
Duplicate of #164

**Closed by balloob** 2020-06-08 17:57 UTC
