### ISSUE TITLE
FFMPEG issues in OS 7.0 or newer on Raspberry Pi 4 64bit

### ISSUE THREAD

**Issue by healeydave** [home-assistant/operating-system#1639] opened 2021-10-27 12:49 UTC
### The problem

Since updating to 2021.10.x, ffmpeg crashes all the time when using HW Acceleration.

I am seeing the problems with the Frigate NVR Integration but after some testing with Blake Blackshear (and several other Rpi 4 users having the same problem), the common denominator seems to be the latest version of HASSOS.

We think it may be limited to Rpi users too. Not sure if running the 64bit version has any relevance.

Blake speculated , "It may be that the new version of Home Assistant OS has some kernel updates that aren't compatible with the way ffmpeg was built. These things are often difficult to track down."

### What version of Home Assistant Core has the issue?

core-2021.10.x

### What was the last working version of Home Assistant Core?

coe-2021.9.x

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Frigate (but only the ffmpeg function)

### Anything in the logs that might be useful for us?

```txt
[2021-10-24 16:14:13] watchdog.Driveway_Bottom       INFO    : Waiting for ffmpeg to exit gracefully...
[2021-10-24 16:14:35] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46018]
[2021-10-24 16:14:37] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:34406]
[2021-10-24 16:14:38] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:34406]
[2021-10-24 16:14:43] watchdog.Driveway_Bottom       INFO    : FFmpeg didnt exit. Force killing...
[2021-10-24 16:14:43] frigate.video                  INFO    : Driveway_Bottom: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2021-10-24 16:14:43] frigate.video                  INFO    : Driveway_Bottom: ffmpeg process is not running. exiting capture thread...
[2021-10-24 16:14:44] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:34408]
[2021-10-24 16:14:45] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:34408]
[2021-10-24 16:14:46] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46018]
[2021-10-24 16:14:53] watchdog.Driveway_Bottom       ERROR   : FFMPEG process crashed unexpectedly for Driveway_Bottom.
[2021-10-24 16:14:53] watchdog.Driveway_Bottom       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2021-10-24 16:14:53] watchdog.Driveway_Bottom       ERROR   : You may have invalid args defined for this camera.
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : [tcp @ 0x559e829e70] Starting connection attempt to 192.168.1.15 port 554
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : [tcp @ 0x559e829e70] Successfully connected to 192.168.1.15 port 554
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : [rtsp @ 0x559e827970] SDP:
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : v=0
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : o=- 1109162014219182 0 IN IP4 0.0.0.0
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : s=HIK Media Server V4.40.017
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : i=HIK Media Server Session Description : standard
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : e=NONE
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : c=IN IP4 0.0.0.0
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : t=0 0
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : a=control:*
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : b=AS:8202
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : a=range:npt=now-
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : m=video 0 RTP/AVP 96
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : i=Video Media
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : a=rtpmap:96 H264/90000
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : a=fmtp:96 profile-level-id=4D0014;packetization-mode=0;sprop-parameter-sets=Z01AM42NQB4AIf/gLcBAQFAAAD6AAAnEDoYAHp8AAA5OHC7y40MAD0+AAAcnDhd5cKA=,aO44gA==
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : a=control:trackID=video
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : b=AS:8192
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : a=Media_header:MEDIAINFO=494D4B48020100000400000100000000000000000000000000000000000000000000000000000000;
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : a=appversion:1.0
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : 
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : [rtsp @ 0x559e827970] setting jitter buffer size to 0
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : [h264 @ 0x559e82aec0] Reinit context to 3840x2160, pix_fmt: yuvj420p
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : Input #0, rtsp, from 'rtsp://admin:PW@192.168.1.15:554/Streaming/channels/201':
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   :   Metadata:
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   :     title           : HIK Media Server V4.40.017
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   :     comment         : HIK Media Server Session Description : standard
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   :   Duration: N/A, start: 1635088433.392144, bitrate: N/A
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   :     Stream #0:0: Video: h264, 1 reference frame, yuvj420p(pc, bt709, progressive, left), 3840x2160 [SAR 1:1 DAR 16:9], 20 fps, 20.33 tbr, 90k tbn, 40 tbc
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : [h264_mp4toannexb @ 0x559e827680] The input looks like it is Annex B already
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : [h264_v4l2m2m @ 0x559e848540] Using device /dev/video10
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : [h264_v4l2m2m @ 0x559e848540] driver 'bcm2835-codec' on card 'bcm2835-codec-decode' in mplane mode
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : [h264_v4l2m2m @ 0x559e848540] requesting formats: output=H264 capture=YU12
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : Stream mapping:
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   :   Stream #0:0 -> #0:0 (h264 (h264_v4l2m2m) -> rawvideo (native))
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : Press [q] to stop, [?] for help
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
[2021-10-24 16:14:53] ffmpeg.Driveway_Bottom.detect  ERROR   : frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
```
```


### Additional information

_No response_

**Comment by agners** [comment] 2021-11-09 16:57
@healeydave which OS version are you using?

Did you try downgrading the OS (using `ha os update --version 6.x`)?

**Comment by healeydave** [comment] 2021-11-10 15:07
> @healeydave which OS version are you using?
> 
> Did you try downgrading the OS (using `ha os update --version 6.x`)?

Hi @agners 
I'm currently on OS to 6.6 and CORE 2021.11.2 
I have read that people that are running HA on a RPi 4 but with a debian build (rather than HA OS) have had success in fixing this issue by downgrading the kernel from 5.10.63 to 5.10.60. 

I'm not sure what version of HA OS I would need to downgrade to for a similar result.

If downgrade HA OS won't cause any issues with being on core-2021.11.2, then I'm happy to give it a go.

I would think the best result would probably be if someone could get to the bottom of the incompatibility with the latest kernel's and incorporate it into the next HA OS update.

**Comment by agners** [comment] 2021-11-10 17:21
> issue by downgrading the kernel from 5.10.63 to 5.10.60.

HAOS 6.6 is using 5.10.17, so a bit older kernel even.

Did that work in any version of HAOS?

**Comment by healeydave** [comment] 2021-11-10 18:49
> > issue by downgrading the kernel from 5.10.63 to 5.10.60.
> 
> HAOS 6.6 is using 5.10.17, so a bit older kernel even.
> 
> Did that work in any version of HAOS?

Yes, I've always run HAOS and had no issues for several months but unfortunately I updated Frigate and Home Assistant in one foul swoop and now I'm (along with lots of others) getting lots of ffmpeg errors when trying to use ffmpeg with hwaccel. Running without hwaccel hits the CPU too hard for me to leave running.

**Comment by agners** [comment] 2021-11-15 10:43
@healeydave you can update to OS `7.0.rc1` (you have to switch to the beta channel temporarily to get the update). I'd suspect its related to the Frigate update, so downgrading Frigate to isolate which update caused the problem might be worth a try.

**Comment by healeydave** [comment] 2021-11-15 15:39
> @healeydave you can update to OS `7.0.rc1` (you have to switch to the beta channel temporarily to get the update). I'd suspect its related to the Frigate update, so downgrading Frigate to isolate which update caused the problem might be worth a try.

Hi agners,
I will update to OS7 and see if the kernel in that still causes any issues with ffmpeg 👍

**Comment by healeydave** [comment] 2021-11-15 18:12
@agners 

Didn't help, re-enabling ffmpeg acceleration causes lots of errors in OS 7.0rc1

**Comment by healeydave** [comment] 2021-11-18 07:55
@agners For Reference:

https://github.com/blakeblackshear/frigate/issues/2030#issuecomment-972619698

**Comment by tomte76** [comment] 2021-12-08 17:53
Same problem here. Today I did a clean install of frigate on a RPI 4 2GB with the latest OS:

`Linux raspberrypi 5.10.63-v8+ #1488 SMP PREEMPT Thu Nov 18 16:16:16 GMT 2021 aarch64 GNU/Linux`

Camera config:

```
Flur:
    ffmpeg:
      global_args: -hide_banner -loglevel info
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m  
      inputs:
        - path: rtsp://192.168.178.67:8554/Flur
          roles:
            - detect
    detect:          
      height: 576
      width: 720
      fps: 5
```

On my setup with loglevel=info I can see the following output:

```
frigate      | [2021-12-08 18:46:24] watchdog.Flur                  INFO    : FFmpeg didnt exit. Force killing...
frigate      | [2021-12-08 18:46:24] frigate.video                  INFO    : Flur: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate      | [2021-12-08 18:46:24] frigate.video                  INFO    : Flur: ffmpeg process is not running. exiting capture thread...
frigate      | [2021-12-08 18:46:34] watchdog.Flur                  ERROR   : FFMPEG process crashed unexpectedly for Flur.
frigate      | [2021-12-08 18:46:34] watchdog.Flur                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate      | [2021-12-08 18:46:34] watchdog.Flur                  ERROR   : You may have invalid args defined for this camera.
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : Input #0, rtsp, from 'rtsp://192.168.178.67:8554/Flur':
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :   Metadata:
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :     title           : LIVE555 Streaming Media v2020.01.19
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :     comment         : LIVE555 Streaming Media v2020.01.19
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :   Duration: N/A, start: 1.200000, bitrate: N/A
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :     Stream #0:0: Video: h264, yuvj420p(pc, bt470bg/bt470bg/bt709, progressive), 720x576, 5 fps, 5 tbr, 90k tbn, 10 tbc
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : [h264_v4l2m2m @ 0x5573af2200] Using device /dev/video10
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : [h264_v4l2m2m @ 0x5573af2200] driver 'bcm2835-codec' on card 'bcm2835-codec-decode' in mplane mode
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : [h264_v4l2m2m @ 0x5573af2200] requesting formats: output=H264 capture=YU12
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : Output #0, flv, to 'rtmp://127.0.0.1/live/Flur':
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :   Metadata:
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :     title           : LIVE555 Streaming Media v2020.01.19
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :     comment         : LIVE555 Streaming Media v2020.01.19
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :     encoder         : Lavf58.45.100
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :     Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuvj420p(pc, bt470bg/bt470bg/bt709, progressive), 720x576, q=2-31, 5 fps, 5 tbr, 1k tbn, 90k tbc
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : Stream mapping:
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :   Stream #0:0 -> #0:0 (copy)
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   :   Stream #0:0 -> #1:0 (h264 (h264_v4l2m2m) -> rawvideo (native))
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : Press [q] to stop, [?] for help
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : [flv @ 0x5573ab4340] Non-monotonous DTS in output stream 0:0; previous: 0, current: -1000; changing to 0. This may result in incorrect timestamps in the output file.
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : [flv @ 0x5573ab4340] Non-monotonous DTS in output stream 0:0; previous: 0, current: -800; changing to 0. This may result in incorrect timestamps in the output file.
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : [flv @ 0x5573ab4340] Non-monotonous DTS in output stream 0:0; previous: 0, current: -600; changing to 0. This may result in incorrect timestamps in the output file.
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : [flv @ 0x5573ab4340] Non-monotonous DTS in output stream 0:0; previous: 0, current: -400; changing to 0. This may result in incorrect timestamps in the output file.
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : [flv @ 0x5573ab4340] Non-monotonous DTS in output stream 0:0; previous: 0, current: -200; changing to 0. This may result in incorrect timestamps in the output file.
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : frame=   32 fps=0.0 q=-1.0 q=0.0 size=     351kB time=00:00:05.00 bitrate= 575.6kbits/s speed=8.96x
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : frame=   35 fps= 30 q=-1.0 q=0.0 size=     361kB time=00:00:05.60 bitrate= 528.3kbits/s speed=4.84x
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : frame=   38 fps= 22 q=-1.0 q=0.0 size=     371kB time=00:00:06.20 bitrate= 490.7kbits/s speed=3.53x
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : frame=   41 fps= 17 q=-1.0 q=0.0 size=     445kB time=00:00:06.80 bitrate= 536.5kbits/s speed=2.89x
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : frame=   44 fps= 15 q=-1.0 q=0.0 size=     457kB time=00:00:07.40 bitrate= 505.7kbits/s speed= 2.5x
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : frame=   47 fps= 13 q=-1.0 q=0.0 size=     467kB time=00:00:08.00 bitrate= 478.6kbits/s speed=2.25x
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : frame=   50 fps= 12 q=-1.0 q=0.0 size=     478kB time=00:00:08.60 bitrate= 455.0kbits/s speed=2.07x
frigate      | [2021-12-08 18:46:34] ffmpeg.Flur.detect             ERROR   : frame=   53 fps= 11 q=-1.0 q=0.0 size=     552kB time=00:00:09.20 bitrate= 491.3kbits/s speed=1.93x
```
works ok, if I disable "hwaccel_args". With hwaccel only a green window.

**Comment by healeydave** [comment] 2021-12-09 10:03
Yeah, I have even subscribed to the beta channel to see if any of the latest developments of HASSOS resolve the crashing  BCM2835 driver but this issue isn't going anywhere anytime soon unfortunately.

I'm following and contributing to a few different GitHub issues relating to this problem and frustratingly, I don't know what else I can do to get this issue taken seriously :(

Its quite destructive too, if hwaccel is left enabled, the amount of errors being posted (below) actually crashes my Home Assistant Rpi after 24 hours and requires a hard power cycle!!

![BCM2835Error](https://user-images.githubusercontent.com/5435141/145375317-851e6239-52cf-4c35-9df8-56753b0e7645.jpg)

**Comment by agners** [comment] 2021-12-09 15:09
Home Assistant Core is unlikely at play here, since the errors are shown by Frigate, which runs in a separate container with a separate ffmpeg version.

Home Assistant Operating System uses the Raspberry Pi provided Linux kernel. It seems plausible that a kernel update caused the ffmpeg version distributed with Frigate to cause problems. The fact that RaspiOS shows the same problem supports that assumption.

In the end, somebody needs to look at ffmpeg distributed Frigate, and make sure its compatible with the latest kernel. As blakeblackshear mentions in https://github.com/blakeblackshear/frigate/issues/2030#issuecomment-977074707, he eventually will do it.

Meanwhile, you have the option to downgrade HAOS. It is fairly save to downgrade, some people run early OS release 5 with the latest Supervisor/Core. Just to be sure I recommend to make a **full backup and download it** before starting the downgrade process.

Ideally you downgrade to the version which was known to still work. If you don't know what it was, you can look through the release notes to see in what versions the kernel got updated  (look for "RaspberryPi: Update kernel "). OS 6.2 might be a good candidate.

To downgrade, open the CLI (e.g. by installing Terminal Add-on) and run:

```
ha os update --version 6.2
```

**Comment by healeydave** [comment] 2021-12-09 15:29
Hi Stefan, 
Thanks for the concise and informative reply.
I'm torn between downgrading HAOS and just waiting for a fix since my installation has advanced quite a bit now since Frigate last worked.

**Comment by jaytea33** [comment] 2021-12-26 14:08
I was really hesitant to downgrade the OS but after tearing my hair out the last few weeks trying to get hwaccel working again and not seeing much movement on this, I bit the bullet and ran this:

ha os update --version 6.6

All seems to be working so far and my CPU usage is finally back down to comfortable levels.

**Comment by agners** [comment] 2021-12-28 09:45
Downgrading is a fairly safe operation with HAOS since we have a read-only, squashfs based root file system.

Between 6.6 and 7.0 we updated the kernel from `1.20210527` to `1.20211029`. From the kernel log, there is a fair amount of changes with `bcm2835-codec` in the title, so I guess that could be the culprit.

**Comment by healeydave** [comment] 2021-12-28 10:05
> Downgrading is a fairly safe operation with HAOS since we have a read-only, squashfs based root file system.
> 
> Between 6.6 and 7.0 we updated the kernel from `1.20210527` to `1.20211029`. From the kernel log, there is a fair amount of changes with `bcm2835-codec` in the title, so I guess that could be the culprit (see https://github.com/raspberrypi/linux/commits/1.20211029).

Thanks for the info Stefan, as the changes to the BCM2835-code seem to be detrimental, who / where would be the right place to report this?

TIA.

**Comment by healeydave** [comment] 2021-12-28 10:29
> I was really hesitant to downgrade the OS but after tearing my hair out the last few weeks trying to get hwaccel working again and not seeing much movement on this, I bit the bullet and ran this:
> 
> ha os update --version 6.6
> 
> All seems to be working so far and my CPU usage is finally back down to comfortable levels.

After reading your post, I bit the bullet and downgraded to 6.6 also but for me it made no difference.
At first I thought everything was good when HA rebooted because my cameras were working but of-course I realised I still had hwaccel hashed out in the config. as soon as I un-remarked the hwacccel settings in config, I had green screen again.

**Comment by healeydave** [comment] 2021-12-28 10:59
> I was really hesitant to downgrade the OS but after tearing my hair out the last few weeks trying to get hwaccel working again and not seeing much movement on this, I bit the bullet and ran this:
> 
> ha os update --version 6.6
> 
> All seems to be working so far and my CPU usage is finally back down to comfortable levels.

I downgraded too today and my system is working again with hwaccel enabled.
I'm running 3 x hikvision cameras and my cpu hovers around 23-27%

I did find an issue with my config, for some reason I was trying to use Frigate with my main-stream instead of my sub-stream. I can only assume when I upgraded to Frigate 2.1 and had to mess with the config because of incompatibility between versions 😩I must have copied the wrong rtsp lines. This is only a guess though since its over 2 months ago that I went through the upgrade woes, I can't remember.

I hope that wasn't the problem all along but given the amount of other users with hwaccel issues, I'm going to assume not 🤔

**Comment by agners** [comment] 2021-12-28 23:28
> Thanks for the info Stefan, as the changes to the BCM2835-code seem to be detrimental, who / where would be the right place to report this, the raspberrypi GitHub mentioned above or maybe somewhere else?

While vanilla Linux has a stable API and strongly follows the mantra "don't break user space", that is often not the case for vendor kernels like the Raspberry Pi kernel. It might work for their use case/with ffmpeg they ship in Raspberry Pi OS. We mix software here, and somebody with a somewhat deep understanding and time needs to investigate what broke. Simply posting an error from a software stack the Raspberry Pi kernel developers are no familiar with is unlikely going to help.

Unfortunately, your log in the original post seems incomplete (I don't see a ffmpeg error, it says `The following ffmpeg logs include the last 100 lines prior to exit.` but there are not 100 lines of ffmpeg output), but glancing at [this comment](https://github.com/blakeblackshear/frigate/issues/1882#issuecomment-935685853), it seems that ffmpeg is failing with: `Error while decoding stream #0:0: Resource temporarily unavailable`.

It seems that something along these lines has been reported with the Raspberry Pi kernel already: https://github.com/raspberrypi/linux/issues/4785. So maybe its a common issue with the new kernel version.

**Comment by tomte76** [comment] 2021-12-29 16:09
I rebuild all the frigate containers "from: debian:stable", added the Raspi-OS repos and used the ffmpeg (which has quite a few patches) and dependencies from Raspi-OS. I can use hwaccel with these containers with 3 cameras on my RPI4 with "Linux iot02 5.10.63-v8+ #1488 SMP PREEMPT Thu Nov 18 16:16:16 GMT 2021 aarch64 GNU/Linux". See also https://github.com/blakeblackshear/frigate/issues/2030.

**Comment by smmoroz** [comment] 2022-01-03 16:17
Hi, all

I've spent few hours trying to fix `ffmpeg` hardware acceleration with the latest HAOS 7.0 and 7.1. It didn't work neither in Frigate container nor in homeassistant container. After that I found this thread, downgraded to HAOS 6.6 and it works again. Thanks for the hint to downgrade.

Best regards,
Sergey.

**Comment by healeydave** [comment] 2022-01-04 08:39
> > Thanks for the info Stefan, as the changes to the BCM2835-code seem to be detrimental, who / where would be the right place to report this, the raspberrypi GitHub mentioned above or maybe somewhere else?
> 
> While vanilla Linux has a stable API and strongly follows the mantra "don't break user space", that is often not the case for vendor kernels like the Raspberry Pi kernel. It might work for their use case/with ffmpeg they ship in Raspberry Pi OS. We mix software here, and somebody with a somewhat deep understanding and time needs to investigate what broke. Simply posting an error from a software stack the Raspberry Pi kernel developers are no familiar with is unlikely going to help.
> 
> Unfortunately, your log in the original post seems incomplete (I don't see a ffmpeg error, it says `The following ffmpeg logs include the last 100 lines prior to exit.` but there are not 100 lines of ffmpeg output), but glancing at [this comment](https://github.com/blakeblackshear/frigate/issues/1882#issuecomment-935685853), it seems that ffmpeg is failing with: `Error while decoding stream #0:0: Resource temporarily unavailable`.
> 
> It seems that something along these lines has been reported with the Raspberry Pi kernel already: [raspberrypi/linux#4785](https://github.com/raspberrypi/linux/issues/4785). So maybe its a common issue with the new kernel version.

Thanks Stefan, fingers crossed a new kernel comes out soon with the fix addressed, because more and more people are downgrading to 6.6 as it fixes everything but I'm concerned we will get to a point where we can't upgrade the core anymore without updating the OS.

**Comment by jgramling17** [comment] 2022-01-18 05:59
To anyone stumbling in this thread looking for a fix:
https://github.com/home-assistant/operating-system/issues/1639#issuecomment-1001188733

This worked perfectly, downgrading the OS a bit is a small tradeoff.

**Comment by MickPBduece** [comment] 2022-01-25 19:38
HA OS 7.1
Core-2021.12.10

I have 7 cameras streaming 2/3 feeds each to a PI4.  I've also encountered the ffmpeg errors before removing acceleration parms.  The camera respond at least as quickly as before the upgrade and removing the parms.
  
![image](https://user-images.githubusercontent.com/47901650/151046543-189ad2d4-56a6-4085-8446-d7643814f02b.png)
and 15% without Frigate.

**Comment by jaytea33** [comment] 2022-01-25 19:46
Not sure if you're still on 7.1 but since the issue is with the Pi kernel itself rather than Frigate and it doesn't seem like much headway is being made by the Pi Team, your best bet is to run this on your 
ha host

ha os update --version 6.6

Idk about you but I'd rather not add the extra stress to the Pi by taking out the hwaccel args. I run a lottt of integrations and add-ons and so far the downgrade hasn't broken any of them

**Comment by healeydave** [comment] 2022-01-26 08:18
@MickPBduece 
Have you tried OS 6.6 with your setup?
It's literally a quick and easy procedure to try, one command line entry and reboot.
If you don't see a significant improvement on OS 6.6 with hwaccel enabled there's noting to stop you re-updating to OS 7.1 or 7.2 afterwards. 

Seeing 136% CPU on your graphic above would be enough for me to not run Frigate (which I did do frustratingly for over a month before I attempted the OS downgrade) because I thought the issue would be addressed quickly (that was back in October). By December I bit the bullet as I didn't want to run without Frigate indefinitely.

**Comment by MickPBduece** [comment] 2022-01-26 16:03
I have not.  I passed thru 6.6 when everyone else did but given that I have
7 cameras with 2-3 feeds each working very reliably and at what I recall is
the same CPU consumption I'm more interested in other things.  My
recollection was that the first camera quit working when I did some
upgrades (likely 7.1) but I also may have made a change to that one camera
yml.  When I removed the global accel parms (per BlakeBlackShear)  that
camera came back online.  Now if I add the accel back all cameras fall
over.
It's my theory that either 7.1 changed something that affects ffmpeg or
somehow 7.1 achieved some awareness and maybe enables the acceleration and
then ffmpeg refuses the parms.
I'm content to wait it out.  HA still runs ahead of its feet from time to
time and Frigate is fresh as well.  It'll all settle out. I'm really most
interested in a new object model.  I really NEED notifications for
squirrels and the occasional fox.

**Comment by healeydave** [comment] 2022-01-26 18:04
I don't think your experiencing the same issue as were are talking about in this thread then.
Usually when you update to 7.x, all the cameras green screen with hwaccel enabled (which is what most of us had configured before the kernel update contained in these 7.x OS releases borked ffmpeg  HW acceleration). If we disable hwaccel all cameras come back online but at the obvious expense of high CPU because of-course hwaccel is not running anymore.

It would have been interesting to see the results of HASS OS6.6 on your system but if you want to stay put, I can't blame you.

Cheers.

**Comment by healeydave** [comment] 2022-02-07 18:16
@agners 
This sounds promising!!
https://github.com/FFmpeg/FFmpeg/commit/3fc72c9fc16df3b7edc329ed9eeaaa1e65976c33

**Comment by jaytea33** [comment] 2022-03-02 06:50
FYI, I just upgraded to Frigate 0.11.0-beta1 since I saw this in the changelog:

"Special early release to fix hardware acceleration for Raspberry Pi 64bit users."

After that I upgraded my HA from 6.6 to 7.4 and I'm happy to report there's no more green screen issue! Just be sure to delete the integration and change the Lovelace card to match the new beta hostname

**Comment by agners** [comment] 2022-03-02 09:09
Thanks for the report.

So this issue got introduced by a change in the Raspberry Pi kernel (which made it into HAOS) and resolved by using a new ffmpeg version in the Frigate add-on (see https://github.com/blakeblackshear/frigate/issues/2030). I am closing this issue here.

**Closed as completed by agners** 2022-03-02 09:09 UTC
Labels: bug, board/raspberrypi, kernel

**Comment by mantaalex** [comment] 2023-01-03 21:31
i even have an rpi 4 with downgraded hass os 6.6 that still doesn't have hwacel working:

`    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://192.168.ip:554/user=admin_password=blablabla_channel=1_stream=0.sdp?real_stream
          roles:
            - detect
            - rtmp
            - record`

**Comment by MickPBduece** [comment] 2023-01-03 22:51
RPI has had issues with this for over a year.
I'm running 7 cameras over 100 devices and a gob of automations and have
37-42 present utilization without the HW accel options because I have an
Coral plugged in.  Frigate and HA run great.  (be sure to get a powered USB
hub as well especially if you have and SSD.

Here' the secret
If you don't have an TPU - you want to get one.   I fought it for a while
but was so lucky my son sent me a Coral.
