### ISSUE TITLE
XU4 stuck because of no partition expansion

### ISSUE THREAD

**Issue by bs2kbs2k** [home-assistant/operating-system#1225] opened 2021-02-13 14:11 UTC
**Hardware Environment**

- [ ] Raspberry Pi [1/2/3/4]
- [x] ODROID XU4
- [ ] ASUS Tinker [S]
- [ ] Intel NUC (or compatible)
- [ ] OVA (Open Virtualization Applicance, on Intel NUC or any other hardware, please add the Hypervisor you are using)

**Home Assistant OS release:**
- [x] Fresh installation of release 5.11
- [ ] Updated from version x.y
- Additional information (if accessible):

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**

log: https://paste.ee/p/w1zjh (dunno which log is this so will put this here)
HA is stuck in config screen infinitely looping trying to download a docker image.  
Tried reflashing twice without luck.
32gb known-good SD card.
inspecting the partitions with gparted said nothing was expanded.

**Comment by agners** [comment] 2021-02-17 09:59
This is a duplicate of https://github.com/home-assistant/operating-system/issues/1193 and will be fixed in 5.12 onwards.

**Closed** 2021-02-18 16:19 UTC
Labels: board/odroid
