### ISSUE TITLE
11.2 broke Audio out via 3,5 jack on Hass Blue (Odroid n2+)

### ISSUE THREAD

**Issue by spudje** [home-assistant/operating-system#3010] opened 2023-12-21 08:21 UTC
### Describe the issue you are experiencing

Since 11.2 the 3.5mm jack analog audio out on the Hass Blue (Odroid N2+) is not working anymore. Both Spotify Connect & Squeezelite leave the output option field in the config empty.

![image](https://github.com/home-assistant/operating-system/assets/53037698/f5068f0a-5ae5-480c-bd42-0e1e14b7153c)

Even after selecting the "default" output and saving, the audio does not work anymore.

Seems more people suffer this issue: https://github.com/hassio-addons/addon-spotify-connect/issues/251

### What operating system image do you use?

odroid-n2 (Hardkernel ODROID-N2/N2+)

### What version of Home Assistant Operating System is installed?

11.2

### Did you upgrade the Operating System.

Yes

### Anything in the Supervisor logs that might be useful for us?

```txt
No, not that I can recognise.
```

### Anything in the Host logs that might be useful for us?

```txt
No, not that I can recognise.
```

### Additional information

Squeezelite log only shows HDMI as possible output:
`[09:34:42] NOTICE: Squeezelite possible outputs(pulse)...
Output devices:
  alsa_output.platform-sound.hdmi-surround71         Built-in Audio Digital Surround 7.1 (HDMI)`

**Comment by sairon** [comment] 2023-12-21 14:31
Duplicate of https://github.com/home-assistant/plugin-audio/issues/157, fix is available in beta and on its way to stable shortly.

**Closed by sairon** 2023-12-21 14:31 UTC
Labels: bug
