### ISSUE TITLE
Operating System 3.13 You are currently running version 4.8

### ISSUE THREAD

**Issue by chris669** [home-assistant/operating-system#721] opened 2020-06-05 05:12 UTC
Seems very strange to me the update message I get on HA:
UPDATE AVAILABLE 
Operating System 3.13
You are currently running version 4.8

**Comment by denniswham** [comment] 2020-06-05 06:02
After updating the OS version is HassOS 3.13 instead of 4.9

**Comment by martymarty004** [comment] 2020-06-05 06:48
Duplicate of #719

**Closed** 2020-06-05 06:56 UTC
