### ISSUE TITLE
HassOS 7.3 does not boot on Intel NUC (i5-10210U)

### ISSUE THREAD

**Issue by nta** [home-assistant/operating-system#1739] opened 2022-02-04 17:00 UTC
### Describe the issue you are experiencing

After upgrading to HassOS 7.3 on the i5-10210U NUC, boot would hang at a random point each time without taking keyboard input (once upon loading `i915` frame buffer, once at a `Mounted systemd ...`).

A few failed boots in, it rolled itself back to 7.2, and it boots again. Yay for A/B installs!

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

7.3

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Use a 10th Gen Intel NUC with 7.2 installed.
2. Upgrade to 7.3.
3. Potentially, the device fails to boot.

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the Host logs that might be useful for us?

```txt
N/A
```

### Additional information

Found one Google result regarding newer Linux 5.10 LTS kernels hanging during boot on Intel systems: https://forum.manjaro.org/t/after-updating-to-kernel-5-10-93-from-5-10-89-the-computer-freezes-at-lenovo-logo/100852

**Comment by agners** [comment] 2022-02-04 20:44
> A few failed boots in, it rolled itself back to 7.2, and it boots again. Yay for A/B installs!

Good to hear that this helped here!

Hm, I have a `NUC7i3DNHE` which I think is a 7th Gen NUC, that successfully updated. That link seems  not to crash randomly though.

So it would completely hang? Did you had to reset the system manually then?

**Comment by nta** [comment] 2022-02-04 21:24
> So it would completely hang? Did you had to reset the system manually then?

Correct. A bit annoying indeed to not have a watchdog.

**Comment by agners** [comment] 2022-02-05 08:26
Does that system happen to have a BNX2/BNX2X firmware? Besides the move from 5.10.91 to 5.10.96 stable kernel release that is the only change.

Do you have external devices connected? Disconnecting everything and see if it comes up without external devices might help isolate in case the problem is triggered by one of those devices.

When you are in OS 7.2, and trigger an OS update again, it will reapply 7.3 to the other partition. So it should be safe to retry as you will be able to go back again with three reboots. In any case. probably worth taking a backup and downloading it before experimenting :sweat_smile:

**Comment by nta** [comment] 2022-02-05 09:27
I can check again later this weekend, hopefully. No Broadcom network cards
attached, no, which indeed would lead to a bad patch in the Linux kernel,
but I find it weird that a LTS kernel would get a breaking change
backported like that.

**Comment by agners** [comment] 2022-02-07 08:35
> but I find it weird that a LTS kernel would get a breaking change
> backported like that.

Most likely it wouldn't be a intentional break. Unfortunately we had breakages before in LTS releases... (USB serial adapters broke a couple of releases ago.

[v5.10.98](https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.10.98) released on Saturday, but not fixes in that direction.

Since revert seems to work in that case, I am going ahead an promote 7.3 to stable still. We can selectively revert if more reports like this come in.

**Comment by agners** [comment] 2022-02-07 09:55
@nta what exact model is that?

**Comment by JackEVE** [comment] 2022-02-07 12:06
Same problem on a nuc NUC10i7FNH running proxmox.
Seems to be boot looping and maxing out one of 2 cpus

**Comment by Espressoshooter** [comment] 2022-02-07 12:31
Same problem for me generic-x86-64.

**Comment by agners** [comment] 2022-02-07 12:55
> Same problem on a nuc NUC10i7FNH running proxmox. Seems to be boot looping and maxing out one of 2 cpus.
> 
> I've been letting in run for a good 10 minutes now without recovering.

I assume HAOS is the virtual guest here? That is somewhat surprising. Are you passing through lots of devices?

**Comment by JackEVE** [comment] 2022-02-07 13:08
> > Same problem on a nuc NUC10i7FNH running proxmox. Seems to be boot looping and maxing out one of 2 cpus.
> > I've been letting in run for a good 10 minutes now without recovering.
> 
> I assume HAOS is the virtual guest here? That is somewhat surprising. Are you passing through lots of devices?

Yes, HAOS is the guest. 
I'm passing a Z-wave stick (Aeotec gen5) and an Arduino (as a MySensors Gateway) through to homeassistant.
I installed proxmox using the standard debian iso and then created a HA VM using this script here: [https://github.com/tteck/Proxmox#-select-a-proxmox-helper-below-](https://github.com/tteck/Proxmox#-select-a-proxmox-helper-below-)
I haven't tried running that script with the new HAOS version, yet.

**Comment by robertboccia** [comment] 2022-02-07 13:35
getting the same issue on my nuc

**Comment by agners** [comment] 2022-02-07 13:37
@robertboccia is it also 10th gen?

**Comment by robertboccia** [comment] 2022-02-07 13:45
> @robertboccia is it also 10th gen?

bxnuc10i7fnh

**Comment by agners** [comment] 2022-02-07 13:54
I removed 7.3 from the stable stream for `generic-x86-64` for now.

**Comment by timborino** [comment] 2022-02-07 22:47
BXNUC10i3FNH1 wouldn't boot after update from 7.2 to 7.3.

Nortek HUSBZB-1, Google Coral, and APC UPS are the only devices connected to the NUC.

I ran the update from the GUI this morning and the system never came back online. Screenshot 1  is how I found the system after attaching a monitor. Keyboard was unresponsive and I had to hold power button down to cycle power. ![1](https://user-images.githubusercontent.com/37837265/152884952-afa14a06-b78f-4b47-8638-0137b8870f75.jpg)

System locked up again (screenshot 2).![2](https://user-images.githubusercontent.com/37837265/152885052-8b4a5b66-d746-4ab7-9ead-1ec3f9d93de2.jpg)

Powered up again with all USB devices disconnected except the keyboard. System locked up again (screenshot 3).![3](https://user-images.githubusercontent.com/37837265/152885083-89e20b63-0b5b-4f0b-9c24-080a7b78a7c9.jpg)

Cycled power again and system came back online with version 7.2.

**Comment by tomlut** [comment] 2022-02-07 23:53
Thanks timborino. I was stuck at the same NTP service. I disconnected my UPS (only USB device other than the keyboard) and after two restarts finally got past this:

![IMG_5672](https://user-images.githubusercontent.com/10679300/152891416-7249feee-1eba-4010-b68e-ab32a228eb99.jpg)

Not sure if it was the number of restarts or disconnecting the UPS but my system rolled back to 7.2 as well. 

NUC11PAHi7

**Comment by nevir** [comment] 2022-02-08 06:57
Similar here with a 10i5FNK1.  Was able to revert back to 7.2 after a few failed boots

**Comment by agners** [comment] 2022-02-08 09:06
@JackEVE do you pass through the WiFi card by chance? If so, your problem is not related to this issue and warrants a separate issue.

Does using 7.2 fixes the problem for you?

**Comment by JackEVE** [comment] 2022-02-08 13:30
> @JackEVE do you pass through the WiFi card by chance? If so, your problem is not related to this issue and warrants a separate issue.
> 
> Does using 7.2 fixes the problem for you?

I'm using a network bridge. 
7.2 works fine.  The issue only showed up when I updated from 7.2 to 7.3

**Comment by agners** [comment] 2022-02-08 19:29
This issue is now fixed with HAOS 7.4 (currently on beta channel). If some of you can confirm that this version works, I'll promote it to stable on Thursday or so.

**Comment by JackEVE** [comment] 2022-02-09 07:13
For me 7.4 is still freezing during boot. Hast to be a different issue in my case, since I am not passing through the wifi card so the fix shouldn't work anyway.

![hassos74_freeze](https://user-images.githubusercontent.com/18036705/153139743-88e6d094-c0f8-4ce1-b351-cc63c80e1b74.PNG)
![hassos74_freeze_hardware](https://user-images.githubusercontent.com/18036705/153140089-5c27a1ce-c797-45c2-9265-c3064a231816.PNG)
![hassos74_freeze_options](https://user-images.githubusercontent.com/18036705/153140094-fb6816fa-69ce-4e98-a2c7-afd22742babf.PNG)

**Comment by robertboccia** [comment] 2022-02-09 07:22
I was not using Wi-Fi either, mine is on lan via ethernet

**Comment by nta** [comment] 2022-02-09 08:40
7.4 boots fine for me again, yes.

**Comment by agners** [comment] 2022-02-10 09:14
The problem was caused by WiFi even when not in use. Thanks for the positive reports.

@JackEVE your problem still seems different, but I also bumped the stable kernel version, so maybe something else fixed it :man_shrugging:

**Closed by agners** 2022-02-10 09:14 UTC
Labels: bug, board/generic-x86-64
