### ISSUE TITLE
Raspberry Pi 4 Model B Rev 1.1, HassOS 4.9 doesn't boot with enable_uart=1

### ISSUE THREAD

**Issue by philrich** [home-assistant/operating-system#725] opened 2020-06-05 12:04 UTC
After OS Upgrade to 4.9 my Raspi 4 didn't boot any more. I have a Raspbee so I have the following in my `config.txt`:

```
enable_uart=1
dtoverlay=pi3-disable-wifi
dtoverlay=pi3-miniuart-bt
```

As soon as I removed above lines from config.txt (Put the sdcard into another linux box, mounted the vfat partition and edited config.txt) a was able to boot but deconz did not work anymore.
I downgraded with `ha os update --version 3.13` and everything is running now.

Version 4.8 was working with `enable_uart=1` but i think a had to boot several times for the raspi to come up. I also had to change the serial device in deconz from `/dev/ttyAMA0` to `/dev/ttyS0`

I don't have a Micro HDMI Cable so i am not able to see what is going on on the console.

**Comment by martymarty004** [comment] 2020-06-06 14:18
Duplicate of #703

**Closed** 2020-06-06 20:38 UTC
