### ISSUE TITLE
Invalid config error!

### ISSUE THREAD

**Issue by mohammad-shadmehr** [home-assistant/operating-system#2294] opened 2023-01-03 11:16 UTC
### Describe the issue you are experiencing

I have been experiencing a very annoying issue with HA for the past couple of months where it often (not always) gives an invalid config error and says it cannot set up cloud, mobile, google assistant, camera. During experiencing this issue the HA cloud will goes away and and the Nabu cassa wont be able to connect to HA

> Setup failed for cloud: Unable to import component: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.10 from "/usr/local/bin/python3" * The NumPy version is: "1.23.2" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library _LR: No such file or directory (needed by /usr/local/lib/python3.10/site-packages/numpy/core/../../numpy.libs/libopenblas_armv8p-r0-8b2c479e.3.20.so)

I have already spent A LOT of time investigating the issue but no luck. The error also prevents me to restart HA and I have to switch it off/on manually which sometimes makes the error go away but it comes back by the next restart.

### What operating system image do you use?

generic-x86-64 (Generic UEFI capable x86-64 systems)

### What version of Home Assistant Operating System is installed?

5.15.76-v8

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

Not really sure how to re-produce the issue it just comes, stay for a while and goes away!

### Anything in the Supervisor logs that might be useful for us?

```txt
3-01-03 18:59:41 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-01-03 19:00:17 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-01-03 19:00:18 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-03 19:00:29 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-01-03 19:00:29 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-01-03 19:06:57 INFO (MainThread) [supervisor.host.info] Updating local host information
23-01-03 19:06:57 INFO (MainThread) [supervisor.host.services] Updating service information
23-01-03 19:06:57 INFO (MainThread) [supervisor.host.network] Updating local network information
23-01-03 19:06:58 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-01-03 19:06:58 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-01-03 19:30:18 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-03 19:59:41 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-01-03 19:59:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-01-03 19:59:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-01-03 19:59:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-01-03 19:59:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-01-03 19:59:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-01-03 19:59:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-01-03 19:59:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-01-03 19:59:41 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-01-03 19:59:41 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-01-03 19:59:41 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-01-03 19:59:42 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-03 19:59:42 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-01-03 19:59:42 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-01-03 20:00:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-01-03 20:00:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-01-03 20:00:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-01-03 20:00:17 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-01-03 20:00:19 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-03 20:00:21 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 0 new - 0 remove
23-01-03 20:00:21 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 0 new - 0 remove
23-01-03 20:00:32 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-01-03 20:00:32 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-01-03 20:30:19 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-03 20:48:08 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-01-03 20:48:09 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
23-01-03 20:48:09 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-01-03 20:55:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 257:None is not WSMsgType.TEXT
23-01-03 20:55:25 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-01-03 20:59:42 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-01-03 21:00:17 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-01-03 21:00:20 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-01-03 21:00:35 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-01-03 21:00:35 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-01-03 21:01:07 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
23-01-03 21:01:07 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from a0d7b954_ssh
23-01-03 21:01:07 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from a0d7b954_ssh
23-01-03 21:01:07 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from a0d7b954_ssh
23-01-03 21:13:38 INFO (MainThread) [supervisor.host.info] Updating local host information
23-01-03 21:13:39 INFO (MainThread) [supervisor.host.services] Updating service information
23-01-03 21:13:39 INFO (MainThread) [supervisor.host.network] Updating local network information
23-01-03 21:13:39 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-01-03 21:13:39 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-01-03 21:30:20 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```

### Anything in the Host logs that might be useful for us?

```txt
Jan 03 10:40:52 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:41:22 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:41:26 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:41:50 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:41:54 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:42:31 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:42:35 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:43:38 homeassistant kernel: audit: type=1334 audit(1672742618.130:298): prog-id=81 op=LOAD
Jan 03 10:43:38 homeassistant kernel: audit: type=1334 audit(1672742618.130:299): prog-id=82 op=LOAD
Jan 03 10:43:38 homeassistant kernel: audit: type=1334 audit(1672742618.130:300): prog-id=83 op=LOAD
Jan 03 10:43:38 homeassistant systemd[1]: Starting Hostname Service...
Jan 03 10:43:38 homeassistant systemd[1]: Started Hostname Service.
Jan 03 10:43:38 homeassistant kernel: audit: type=1334 audit(1672742618.614:301): prog-id=84 op=LOAD
Jan 03 10:43:38 homeassistant kernel: audit: type=1334 audit(1672742618.614:302): prog-id=85 op=LOAD
Jan 03 10:43:38 homeassistant kernel: audit: type=1334 audit(1672742618.614:303): prog-id=86 op=LOAD
Jan 03 10:43:38 homeassistant systemd[1]: Starting Time & Date Service...
Jan 03 10:43:39 homeassistant systemd[1]: Started Time & Date Service.
Jan 03 10:43:39 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:43:41 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:43:51 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:43:53 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:44:08 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Jan 03 10:44:08 homeassistant kernel: audit: type=1334 audit(1672742648.734:304): prog-id=0 op=UNLOAD
Jan 03 10:44:08 homeassistant kernel: audit: type=1334 audit(1672742648.734:305): prog-id=0 op=UNLOAD
Jan 03 10:44:08 homeassistant kernel: audit: type=1334 audit(1672742648.734:306): prog-id=0 op=UNLOAD
Jan 03 10:44:09 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
Jan 03 10:44:09 homeassistant kernel: audit: type=1334 audit(1672742649.562:307): prog-id=0 op=UNLOAD
Jan 03 10:44:09 homeassistant kernel: audit: type=1334 audit(1672742649.562:308): prog-id=0 op=UNLOAD
Jan 03 10:44:09 homeassistant kernel: audit: type=1334 audit(1672742649.562:309): prog-id=0 op=UNLOAD
Jan 03 10:44:31 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:44:33 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:46:32 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:46:34 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:47:47 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:47:49 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:47:51 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:47:53 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:49:52 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:49:54 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:50:32 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:50:34 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:51:51 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:51:55 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:52:31 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:52:35 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:52:57 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:53:02 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:53:52 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:53:56 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:55:07 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:55:11 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:55:53 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:55:55 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:56:21 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:56:25 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:56:31 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:56:33 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:57:38 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:57:42 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:57:52 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:57:58 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:58:00 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:58:02 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:58:04 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:58:08 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:58:32 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:58:34 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:58:46 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:58:50 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 10:59:21 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 10:59:25 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:00:31 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:00:35 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:01:13 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:01:17 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:02:32 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:02:34 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:03:51 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:03:57 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:04:05 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:04:09 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:04:31 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:04:35 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:04:39 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:04:41 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:07:18 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:07:22 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:07:55 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:07:59 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:08:31 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:08:35 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:09:56 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:09:58 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:11:10 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:11:14 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:11:28 homeassistant kernel: audit: type=1334 audit(1672744288.762:310): prog-id=87 op=LOAD
Jan 03 11:11:28 homeassistant systemd[1]: Started Journal Gateway Service.
Jan 03 11:11:29 homeassistant systemd-journal-gatewayd[8234]: microhttpd: MHD_OPTION_EXTERNAL_LOGGER is not the first option specified for the daemon. Some messages may be printed by the standard MHD logger.
Jan 03 11:11:30 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:11:34 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:11:36 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
Jan 03 11:11:44 homeassistant kernel: hwmon hwmon1: Voltage normalised
Jan 03 11:11:48 homeassistant kernel: hwmon hwmon1: Undervoltage detected!
```

### System information

<html>
<body>

Version | core-2022.12.9
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.7
Operating System Family | Linux
Operating System Version | 5.15.76-v8
CPU Architecture | aarch64
Timezone | Australia/Adelaide
Configuration Directory | /config

</body>
</html>

**Comment by frenck** [comment] 2023-01-03 11:32
Incorrect repository, duplicate of https://github.com/home-assistant/core/issues/84595

**Closed by frenck** 2023-01-03 11:32 UTC
Labels: bug
