### ISSUE TITLE
OS 12.2 broke HDMI-CEC

### ISSUE THREAD

**Issue by andybjackson** [home-assistant/operating-system#3304] opened 2024-04-12 07:58 UTC
### Describe the issue you are experiencing

After upgrading to OS 12.2, Home Assistant now reports setup error regarding HDMI-CEC. Looking at the error message suggests this is a permissions issue.

### What operating system image do you use?

odroid-n2 (Hardkernel ODROID-N2/N2+)

### What version of Home Assistant Operating System is installed?

12.2

### Did you upgrade the Operating System.

Yes

### Steps to reproduce the issue

1. Boot Home Assistant.
2. See Setup error.

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-04-12 04:05:28.253 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-04-12 04:05:28.263 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-04-12 04:05:28.264 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-04-12 04:05:28.264 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-04-12 04:05:28.265 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-04-12 04:05:28.380 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-04-12 04:05:28.381 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-04-12 04:05:28.381 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-04-12 04:06:46.766 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-12 04:36:46.939 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-12 05:05:28.394 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-04-12 05:05:28.395 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-04-12 05:05:28.395 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-04-12 05:05:28.395 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-04-12 05:05:28.395 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-04-12 05:05:28.396 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-04-12 05:05:28.449 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-04-12 05:05:28.451 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-04-12 05:05:28.461 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-04-12 05:05:28.462 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-04-12 05:05:28.462 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-04-12 05:05:28.462 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-04-12 05:05:28.586 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-04-12 05:05:28.586 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-04-12 05:05:28.587 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-04-12 05:06:45.201 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-04-12 05:06:46.511 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
2024-04-12 05:06:46.514 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
2024-04-12 05:06:46.520 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
2024-04-12 05:06:47.124 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-12 05:06:48.145 INFO (MainThread) [supervisor.store] Loading add-ons from store: 77 all - 0 new - 0 remove
2024-04-12 05:06:48.145 INFO (MainThread) [supervisor.store] Loading add-ons from store: 77 all - 0 new - 0 remove
2024-04-12 05:26:46.429 INFO (MainThread) [supervisor.host.info] Updating local host information
2024-04-12 05:26:46.968 INFO (MainThread) [supervisor.host.services] Updating service information
2024-04-12 05:26:46.982 INFO (MainThread) [supervisor.host.network] Updating local network information
2024-04-12 05:26:47.128 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
2024-04-12 05:26:47.136 INFO (MainThread) [supervisor.host.manager] Host information reload completed
2024-04-12 05:36:47.308 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-12 06:05:28.601 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-04-12 06:05:28.602 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-04-12 06:05:28.603 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-04-12 06:05:28.603 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-04-12 06:05:28.603 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-04-12 06:05:28.604 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-04-12 06:05:28.656 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-04-12 06:05:28.657 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-04-12 06:05:28.665 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-04-12 06:05:28.667 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-04-12 06:05:28.668 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-04-12 06:05:28.668 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-04-12 06:05:28.786 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-04-12 06:05:28.787 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-04-12 06:05:28.788 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-04-12 06:06:47.483 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-12 06:36:47.669 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-12 07:05:28.798 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-04-12 07:05:28.799 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-04-12 07:05:28.800 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-04-12 07:05:28.800 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-04-12 07:05:28.800 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-04-12 07:05:28.801 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-04-12 07:05:28.851 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-04-12 07:05:28.851 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-04-12 07:05:28.861 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-04-12 07:05:28.862 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-04-12 07:05:28.862 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-04-12 07:05:28.863 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-04-12 07:05:29.010 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-04-12 07:05:29.011 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-04-12 07:05:29.011 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-04-12 07:06:45.359 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-04-12 07:06:47.861 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-12 07:33:27.139 INFO (MainThread) [supervisor.host.info] Updating local host information
2024-04-12 07:33:27.685 INFO (MainThread) [supervisor.host.services] Updating service information
2024-04-12 07:33:27.693 INFO (MainThread) [supervisor.host.network] Updating local network information
2024-04-12 07:33:27.818 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
2024-04-12 07:33:27.825 INFO (MainThread) [supervisor.host.manager] Host information reload completed
2024-04-12 07:36:48.041 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-12 08:05:29.029 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-04-12 08:05:29.029 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-04-12 08:05:29.030 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-04-12 08:05:29.030 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-04-12 08:05:29.030 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-04-12 08:05:29.031 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-04-12 08:05:29.093 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-04-12 08:05:29.094 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-04-12 08:05:29.102 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-04-12 08:05:29.103 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-04-12 08:05:29.104 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-04-12 08:05:29.105 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-04-12 08:05:29.251 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-04-12 08:05:29.253 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-04-12 08:05:29.253 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-04-12 08:06:48.150 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
2024-04-12 08:06:48.153 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
2024-04-12 08:06:48.161 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
2024-04-12 08:06:48.214 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-04-12 08:06:49.601 INFO (MainThread) [supervisor.store] Loading add-ons from store: 77 all - 0 new - 0 remove
2024-04-12 08:06:49.601 INFO (MainThread) [supervisor.store] Loading add-ons from store: 77 all - 0 new - 0 remove
2024-04-12 08:36:48.394 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```

### Anything in the Host logs that might be useful for us?

```txt
2024-04-11 22:07:15.296 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
2024-04-11 22:07:15.410 homeassistant kernel: audit: type=1334 audit(1712873235.403:229): prog-id=63 op=UNLOAD
2024-04-11 22:07:15.410 homeassistant kernel: audit: type=1334 audit(1712873235.403:230): prog-id=62 op=UNLOAD
2024-04-11 22:07:15.410 homeassistant kernel: audit: type=1334 audit(1712873235.403:231): prog-id=61 op=UNLOAD
2024-04-11 22:07:15.569 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
2024-04-11 22:07:15.586 homeassistant kernel: audit: type=1334 audit(1712873235.579:232): prog-id=66 op=UNLOAD
2024-04-11 22:07:15.586 homeassistant kernel: audit: type=1334 audit(1712873235.579:233): prog-id=65 op=UNLOAD
2024-04-11 22:07:15.586 homeassistant kernel: audit: type=1334 audit(1712873235.579:234): prog-id=64 op=UNLOAD
2024-04-11 22:20:04.192 homeassistant systemd[1]: Starting Cleanup of Temporary Directories...
2024-04-11 22:20:04.243 homeassistant systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
2024-04-11 22:20:04.244 homeassistant systemd[1]: Finished Cleanup of Temporary Directories.
2024-04-12 00:13:24.974 homeassistant kernel: audit: type=1334 audit(1712880804.966:235): prog-id=67 op=LOAD
2024-04-12 00:13:24.974 homeassistant kernel: audit: type=1334 audit(1712880804.966:236): prog-id=68 op=LOAD
2024-04-12 00:13:24.974 homeassistant kernel: audit: type=1334 audit(1712880804.966:237): prog-id=69 op=LOAD
2024-04-12 00:13:24.998 homeassistant systemd[1]: Starting Hostname Service...
2024-04-12 00:13:25.238 homeassistant systemd[1]: Started Hostname Service.
2024-04-12 00:13:25.250 homeassistant kernel: audit: type=1334 audit(1712880805.242:238): prog-id=70 op=LOAD
2024-04-12 00:13:25.250 homeassistant kernel: audit: type=1334 audit(1712880805.242:239): prog-id=71 op=LOAD
2024-04-12 00:13:25.250 homeassistant kernel: audit: type=1334 audit(1712880805.242:240): prog-id=72 op=LOAD
2024-04-12 00:13:25.290 homeassistant systemd[1]: Starting Time & Date Service...
2024-04-12 00:13:25.507 homeassistant systemd[1]: Started Time & Date Service.
2024-04-12 00:13:55.272 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
2024-04-12 00:13:55.410 homeassistant kernel: audit: type=1334 audit(1712880835.403:241): prog-id=69 op=UNLOAD
2024-04-12 00:13:55.410 homeassistant kernel: audit: type=1334 audit(1712880835.403:242): prog-id=68 op=UNLOAD
2024-04-12 00:13:55.410 homeassistant kernel: audit: type=1334 audit(1712880835.403:243): prog-id=67 op=UNLOAD
2024-04-12 00:13:55.545 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
2024-04-12 00:13:55.566 homeassistant kernel: audit: type=1334 audit(1712880835.559:244): prog-id=72 op=UNLOAD
2024-04-12 00:13:55.566 homeassistant kernel: audit: type=1334 audit(1712880835.559:245): prog-id=71 op=UNLOAD
2024-04-12 00:13:55.566 homeassistant kernel: audit: type=1334 audit(1712880835.559:246): prog-id=70 op=UNLOAD
2024-04-12 02:20:05.730 homeassistant kernel: audit: type=1334 audit(1712888405.723:247): prog-id=73 op=LOAD
2024-04-12 02:20:05.730 homeassistant kernel: audit: type=1334 audit(1712888405.723:248): prog-id=74 op=LOAD
2024-04-12 02:20:05.730 homeassistant kernel: audit: type=1334 audit(1712888405.723:249): prog-id=75 op=LOAD
2024-04-12 02:20:05.751 homeassistant systemd[1]: Starting Hostname Service...
2024-04-12 02:20:05.969 homeassistant systemd[1]: Started Hostname Service.
2024-04-12 02:20:05.990 homeassistant kernel: audit: type=1334 audit(1712888405.983:250): prog-id=76 op=LOAD
2024-04-12 02:20:05.990 homeassistant kernel: audit: type=1334 audit(1712888405.983:251): prog-id=77 op=LOAD
2024-04-12 02:20:05.990 homeassistant kernel: audit: type=1334 audit(1712888405.983:252): prog-id=78 op=LOAD
2024-04-12 02:20:06.023 homeassistant systemd[1]: Starting Time & Date Service...
2024-04-12 02:20:06.235 homeassistant systemd[1]: Started Time & Date Service.
2024-04-12 02:20:36.004 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
2024-04-12 02:20:36.106 homeassistant kernel: audit: type=1334 audit(1712888436.101:253): prog-id=75 op=UNLOAD
2024-04-12 02:20:36.106 homeassistant kernel: audit: type=1334 audit(1712888436.101:254): prog-id=74 op=UNLOAD
2024-04-12 02:20:36.106 homeassistant kernel: audit: type=1334 audit(1712888436.101:255): prog-id=73 op=UNLOAD
2024-04-12 02:20:36.276 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
2024-04-12 02:20:36.298 homeassistant kernel: audit: type=1334 audit(1712888436.293:256): prog-id=78 op=UNLOAD
2024-04-12 02:20:36.298 homeassistant kernel: audit: type=1334 audit(1712888436.293:257): prog-id=77 op=UNLOAD
2024-04-12 02:20:36.298 homeassistant kernel: audit: type=1334 audit(1712888436.293:258): prog-id=76 op=UNLOAD
2024-04-12 03:58:15.024 homeassistant NetworkManager[433]: <info>  [1712894295.0244] dhcp6 (end0): state changed new lease, address=fda2:664a:a798::ba3 2a02:8012:729c::ba3
2024-04-12 03:58:15.067 homeassistant systemd[1]: Starting Network Manager Script Dispatcher Service...
2024-04-12 03:58:15.076 homeassistant systemd[1]: Started Network Manager Script Dispatcher Service.
2024-04-12 03:58:25.098 homeassistant systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
2024-04-12 04:05:21.966 homeassistant NetworkManager[433]: <info>  [1712894721.9661] dhcp4 (end0): state changed new lease, address=192.168.2.248
2024-04-12 04:05:22.014 homeassistant systemd[1]: Starting Network Manager Script Dispatcher Service...
2024-04-12 04:05:22.033 homeassistant systemd[1]: Started Network Manager Script Dispatcher Service.
2024-04-12 04:05:32.052 homeassistant systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
2024-04-12 04:11:08.829 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8ae32e63c538fefd4baf27976f4ac8bb69f8f033dc583408db5aabb840458bc4-runc.QiTlEr.mount: Deactivated successfully.
2024-04-12 04:11:29.028 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8ae32e63c538fefd4baf27976f4ac8bb69f8f033dc583408db5aabb840458bc4-runc.eHZFPl.mount: Deactivated successfully.
2024-04-12 04:11:39.136 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8ae32e63c538fefd4baf27976f4ac8bb69f8f033dc583408db5aabb840458bc4-runc.FBZETG.mount: Deactivated successfully.
2024-04-12 04:26:46.442 homeassistant kernel: audit: type=1334 audit(1712896006.434:259): prog-id=79 op=LOAD
2024-04-12 04:26:46.442 homeassistant kernel: audit: type=1334 audit(1712896006.434:260): prog-id=80 op=LOAD
2024-04-12 04:26:46.442 homeassistant kernel: audit: type=1334 audit(1712896006.434:261): prog-id=81 op=LOAD
2024-04-12 04:26:46.478 homeassistant systemd[1]: Starting Hostname Service...
2024-04-12 04:26:46.698 homeassistant systemd[1]: Started Hostname Service.
2024-04-12 04:26:46.710 homeassistant kernel: audit: type=1334 audit(1712896006.702:262): prog-id=82 op=LOAD
2024-04-12 04:26:46.710 homeassistant kernel: audit: type=1334 audit(1712896006.702:263): prog-id=83 op=LOAD
2024-04-12 04:26:46.710 homeassistant kernel: audit: type=1334 audit(1712896006.702:264): prog-id=84 op=LOAD
2024-04-12 04:26:46.727 homeassistant systemd[1]: Starting Time & Date Service...
2024-04-12 04:26:46.938 homeassistant systemd[1]: Started Time & Date Service.
2024-04-12 04:27:16.732 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
2024-04-12 04:27:16.878 homeassistant kernel: audit: type=1334 audit(1712896036.871:265): prog-id=81 op=UNLOAD
2024-04-12 04:27:16.878 homeassistant kernel: audit: type=1334 audit(1712896036.871:266): prog-id=80 op=UNLOAD
2024-04-12 04:27:16.878 homeassistant kernel: audit: type=1334 audit(1712896036.871:267): prog-id=79 op=UNLOAD
2024-04-12 04:27:16.976 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
2024-04-12 04:27:17.010 homeassistant kernel: audit: type=1334 audit(1712896037.003:268): prog-id=84 op=UNLOAD
2024-04-12 04:27:17.010 homeassistant kernel: audit: type=1334 audit(1712896037.003:269): prog-id=83 op=UNLOAD
2024-04-12 04:27:17.010 homeassistant kernel: audit: type=1334 audit(1712896037.003:270): prog-id=82 op=UNLOAD
2024-04-12 06:12:05.484 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-8ae32e63c538fefd4baf27976f4ac8bb69f8f033dc583408db5aabb840458bc4-runc.rlT1cr.mount: Deactivated successfully.
2024-04-12 06:33:27.150 homeassistant kernel: audit: type=1334 audit(1712903607.143:271): prog-id=85 op=LOAD
2024-04-12 06:33:27.150 homeassistant kernel: audit: type=1334 audit(1712903607.143:272): prog-id=86 op=LOAD
2024-04-12 06:33:27.150 homeassistant kernel: audit: type=1334 audit(1712903607.143:273): prog-id=87 op=LOAD
2024-04-12 06:33:27.175 homeassistant systemd[1]: Starting Hostname Service...
2024-04-12 06:33:27.410 homeassistant systemd[1]: Started Hostname Service.
2024-04-12 06:33:27.430 homeassistant kernel: audit: type=1334 audit(1712903607.423:274): prog-id=88 op=LOAD
2024-04-12 06:33:27.430 homeassistant kernel: audit: type=1334 audit(1712903607.423:275): prog-id=89 op=LOAD
2024-04-12 06:33:27.434 homeassistant kernel: audit: type=1334 audit(1712903607.427:276): prog-id=90 op=LOAD
2024-04-12 06:33:27.459 homeassistant systemd[1]: Starting Time & Date Service...
2024-04-12 06:33:27.650 homeassistant systemd[1]: Started Time & Date Service.
2024-04-12 06:33:57.445 homeassistant systemd[1]: systemd-hostnamed.service: Deactivated successfully.
2024-04-12 06:33:57.546 homeassistant kernel: audit: type=1334 audit(1712903637.540:277): prog-id=87 op=UNLOAD
2024-04-12 06:33:57.546 homeassistant kernel: audit: type=1334 audit(1712903637.540:278): prog-id=86 op=UNLOAD
2024-04-12 06:33:57.546 homeassistant kernel: audit: type=1334 audit(1712903637.540:279): prog-id=85 op=UNLOAD
2024-04-12 06:33:57.692 homeassistant systemd[1]: systemd-timedated.service: Deactivated successfully.
2024-04-12 06:33:57.726 homeassistant kernel: audit: type=1334 audit(1712903637.720:280): prog-id=90 op=UNLOAD
2024-04-12 06:33:57.726 homeassistant kernel: audit: type=1334 audit(1712903637.720:281): prog-id=89 op=UNLOAD
2024-04-12 06:33:57.726 homeassistant kernel: audit: type=1334 audit(1712903637.720:282): prog-id=88 op=UNLOAD
2024-04-12 07:53:26.346 homeassistant dockerd[509]: 2024/04/12 07:53:26 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98)
2024-04-12 07:53:26.495 homeassistant dockerd[509]: 2024/04/12 07:53:26 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*respWriterWrapper).WriteHeader (wrap.go:98)
2024-04-12 07:56:09.622 homeassistant kernel: audit: type=1334 audit(1712908569.614:283): prog-id=91 op=LOAD
2024-04-12 07:56:09.625 homeassistant systemd-timesyncd[495]: Network configuration changed, trying to establish connection.
2024-04-12 07:56:09.650 homeassistant systemd-timesyncd[495]: Contacted time server 162.159.200.123:123 (time.cloudflare.com).
2024-04-12 07:56:09.650 homeassistant systemd[1]: Started Journal Gateway Service.
```

## System Information

version | core-2024.4.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1401
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 2 May 2024 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-8.ui.nabu.casa
certificate_status | ready
instance_id | 844c784ce7c542129273a4ada2a489ea
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 113.9 GB
disk_used | 36.2 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), ESPHome (2024.3.2), Samba share (12.3.1), Terminal & SSH (9.11.0), Matter Server (5.5.1), Silicon Labs Multiprotocol (2.4.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 April 2024 at 19:24
-- | --
current_recorder_run | 11 April 2024 at 23:05
estimated_db_size | 205.34 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Additional information

Log Details (ERROR)
Logger: homeassistant.setup
Source: setup.py:398
First occurred: 11 April 2024 at 23:06:04 (1 occurrences)
Last logged: 11 April 2024 at 23:06:04

Error during setup of component hdmi_cec
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 398, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hdmi_cec/__init__.py", line 207, in setup
    hdmi_network = HDMINetwork(adapter, loop=loop)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycec/network.py", line 309, in __init__
    self._command_queue = Queue()
                          ^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 103, in Queue
    return Queue(maxsize, ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/queues.py", line 43, in __init__
    self._rlock = ctx.Lock()
                  ^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/synchronize.py", line 169, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/local/lib/python3.12/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system

**Comment by sairon** [comment] 2024-04-12 08:17
Duplicate of #3277. This has been fixed through the latest Supervisor update. Note that `ha core rebuld` is also needed, for details see: https://github.com/home-assistant/supervisor/issues/4996

**Closed by sairon** 2024-04-12 08:17 UTC
Labels: bug

**Comment by eporsche** [comment] 2024-05-08 15:44
I am still facing this issue:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hdmi_cec/__init__.py", line 207, in setup
    hdmi_network = HDMINetwork(adapter, loop=loop)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pycec/network.py", line 309, in __init__
    self._command_queue = Queue()
                          ^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 103, in Queue
    return Queue(maxsize, ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/queues.py", line 43, in __init__
    self._rlock = ctx.Lock()
                  ^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/synchronize.py", line 169, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/local/lib/python3.12/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system`

Core
2024.5.2
Supervisor
2024.05.1
Operating System
12.3
Frontend
20240501.1

I tried `ha core rebuild ` but without success. Only workaround is to downgrade haos to version 12.1 with `ha os update --version 12.1`
